### ISSUE TITLE
PPanGGOLiN taking too much time to run on large collection of genomes

### ISSUE THREAD

**Issue by theabhirath** [labgem/PPanGGOLiN#101]
Hi, I've been trying to use the tool for a collection of about 12k genomes. I ran it with around 40 CPUs, and the job has been running for about two days now, with the output file only showing that it has started annotating the genomes. The wiki suggests that this should not be the case. A smaller run with around 2.7k genomes worked perfectly, so I'm a little unclear about what could be going wrong. Is there any other way to speed the run up? I am already using the `--cpu` option, and the output file does indicate that 40 CPUs are being used.

**Comment by axbazin** [comment]
Hi,

The "genome annotation" step is probably the least optimizable step of ppanggolin. Its speed will increase linearly with the number of CPUs.

It should take about 10-15s per genome per CPU maximum on 'large' microbial genomes like pseudomonas or burkholderia, so roughly 2h max?

If the process is still going, and you've got progress bars displayed, is it stuck on a particular genome? Or do you still see it processing genomes, eventually at a slower pace? (there should be some indication of the number of genomes per seconds being processes)
Are the CPUs of the machine on which ppanggolin is running being used properly?

Adelme

**Comment by axbazin** [comment]
if you're running through a slurm cluster the progress bar might go to the error output file.
Otherwise, disabling the progress bar is a parameter to set (-d) by default they should be activated.

**Comment by axbazin** [comment]
Ah, I forgot something: if you redirect the log to anything else than stdout (using --log), then it disables the progress bars as well

**Comment by theabhirath** [comment]
Hi, thanks so much for the help with the debugging! I figured out that when I allocated the CPUs on the same compute node on the cluster, the timings were much closer to what you had suggested. Is this expected behaviour? (For context, 8 CPUs across 5 nodes was slow, while 40 CPUs on the same node was fast).

**Comment by axbazin** [comment]
Yes it's expected as ppanggolin is not designed to run on multiple nodes at once. What likely happened when you tried to run it on multiple nodes is that it ran on one of the nodes, with the allocated ressources, and nothing ran on the others.
Glad it worked in the end !
