### ISSUE TITLE
Extract gene IDs located within RGPs

### ISSUE THREAD

**Issue by genomesandMGEs** [labgem/PPanGGOLiN#103]
Hi Adelme,

Really enjoying exploring all the things one can do with this tool - really cool!

I ran pangenome analysis with panrgp, and would like to know if it's possible to extract a file listing all the genes located within the RGPs. I noticed that the plastic regions file lists the genome, contig, number of genes, etc. located within identified RGPs, but doesn't list the actual gene IDs. Is there a workaround? I'm sorry in advance if I'm missing something.

Many thanks!

**Comment by axbazin** [comment]
Hi,

Thank you for your kind words, once again ;) 

Do you mean all the genes located within all RGPs, or all the genes within each RGP separately?
In any case, there is no easy "file listing" to obtain, but you can get them with some workarounds:

If you mean all genes among all RGPs, I would use the 'fasta' subcommand:

```ppanggolin fasta -p pangenome.h5 --output MY_GENES --genes rgp```

And then grep the gene IDs ``` grep '>' MY_GENES/rgp_genes.fna```

If you mean all genes with each RGP separately, it's not as easy, but you can use the fact that the RGP ID is written in the "projection" files.

you get them as such:

```ppanggolin write -p pangenome.h5 --projection```

And the RGP ids appear in the 13th column of the .txt files written in the 'projection' folder. As such, if you only get lines where there is a value in the 13th column, you basically have an association between RGP_ID and gene_ID.

Sadly the doc is not yet up to date with those additional columns in the 'projection' files, so no one could guess, but soonish hopefully.

Adelme

**Comment by genomesandMGEs** [comment]
Thanks for the quick reply! This 13th column you mention was added in a latest release? Unfortunately, these pangenomes were performed with a somehow old version (1.1.136), and it appears the projection files only have 12 columns. Are you aware of any other solution, that doesn't imply rerunning `panrgp` with the latest release?

**Comment by axbazin** [comment]
Indeed, it's with the latest release only.

You should still be able to use the lastest version on the pangenome.h5 file generated with 1.1.136 ;

I'd go with installing the latest version, then run the following:

```ppanggolin write -p pangenome.h5 --projection --output my_projections```

It should work as the information it reads were already stored in the hdf5 in 1.1.136

**Comment by genomesandMGEs** [comment]
Thanks! This is exactly what I need :)

**Comment by JeanMainguy** [comment]
Hi, 

Version 1.2.96 isn't an official release of PPanGGOLiN. Do you mean version 1.1.96? 🤔
Since we launched version 2 in January, we're focusing on that and won't be able to debug version 1. I'd highly recommend updating to version 2 ! 🚀

Thanks
