### ISSUE TITLE
Only extract gene families within RGPs

### ISSUE THREAD

**Issue by genomesandMGEs** [labgem/PPanGGOLiN#104]
Hi (again) Adelme,

Using `ppanggolin write -p pangenome.h5 --families_tsv` it's possible to extract gene families for the entire pangenome. But is it possible to extract only gene families from RGPs?

Many thanks!

**Comment by axbazin** [comment]
Hi again,

You can use an equivalent workaround for gene families using "fasta" as well, with the "--prot_families" or "--gene_families" option instead of "--genes", or the "projection" file, pretty much like in your other issue (if others stumble into this, I mean: #103 ), except by using the 7th column of the projection files rather than the 1st.

I hope everything is clear and that it was what you were looking for!

Adelme

**Comment by genomesandMGEs** [comment]
Thanks for the reply Adelme, but I guess I didn't explain well what I need. I ran `ppanggolin fasta -p pangenome.h5 --gene_families rgp -o test`, and this extracts representative nucleotide sequences of gene families across RGPs. If I understood correctly, this step fetches a representative from clusters of genes located solely in RGPs. Is this correct? If so, I would like to use a command similar to this `ppanggolin write -p pangenome.h5 --families_tsv --gene_families rgp`, so that I could have a tsv file providing the association between RGP genes and RGP gene families.

**Comment by axbazin** [comment]
Ah I see, yes you are correct it uses a representative from the clusters of genes in RGPs.

In that case I'd still write this fasta, then something like this:
```
grep '>' rgp_gene_families.fna | sed 's/>//g' > rgp_gene_families_ids.txt

grep -f rgp_gene_families_ids.txt gene_families.tsv | cut -f 1
```

It should get you the corresponding gene families, and hopefully with that what you need?

**Comment by genomesandMGEs** [comment]
Thanks Adelme! I was actually doing this now, but was just wondering if it would be possible to do that directly with `ppanggolin write` since I have very large files. But this will work as well :)

**Comment by axbazin** [comment]
I'm afraid not, it's not really designed to filter anything, only to write raw output files
