### ISSUE TITLE
Locus tag missing from projection file

### ISSUE THREAD

**Issue by ezherman** [labgem/PPanGGOLiN#126]
I've been enjoying using PPanGGoLiN, thank you for developing this workflow! I have discovered that a locus tag of interest, which can be found in my .gbff file, cannot be found in the sample's projections file. I was hoping to check whether this is expected behaviour. 

The .gbff file comes from RefSeq. It belongs to isolate GCF_900143905.1. The file can be downloaded [here](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/143/905/GCF_900143905.1_77/GCF_900143905.1_77_genomic.gbff.gz).

The .gbff file contains the locus tag BUR30_RS17525, with the following annotation:

```
gene            10294..>11102
                     /locus_tag="BUR30_RS17525"
     CDS             10294..>11102
                     /locus_tag="BUR30_RS17525"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_250734.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DUF3857 domain-containing protein"
                     /protein_id="WP_139264129.1"
                     /translation="MPRHPFSPSFLAASVFCAATPALAALQPIAEAPLAGETEFRCQF
                     NADNSTDCVSTYSFTILKPSGREMLSRIDRSYAETDSLIVEKAELTQPGGKPVPLDQS
                     QIDTRTAPNPDQGFLRERQTSLAFPNLRVGTRISYTLREHFTAKPLSTQFHYILSRPP
                     MPVRDDRFVAEFKAERPIFVRSELMDAYRIEQSADKKTLKVSLKKPQYTNYINEAGNA
                     YLRHTPRLELGSSLDLQDNFGPFAARYNEILAAELPKGAAAAVAAVKGKPAR"
```

The projections file, available to download [here](https://drive.proton.me/urls/QX64FPZK5M#xEZFoUROFMDp), does not contain the locus tag. Neither does the gene_families file (available [here](https://drive.proton.me/urls/AWF9E4CWW4#2HE9uC47NfQv)). 

I ran PPanGGOLiN using the following commands:
```
ppanggolin all -f --anno results/intermediate/ppanggolin_gbff_input.tsv --cpu 7 --output results/intermediate/ppanggolin > results/intermediate/ppanggolin/log.txt
ppanggolin write -f --families_tsv -p results/intermediate/ppanggolin/pangenome.h5 --output results/intermediate/ppanggolin > results/intermediate/ppanggolin/log.txt 
ppanggolin write -f --projection -p results/intermediate/ppanggolin/pangenome.h5 --output results/intermediate/ppanggolin > results/intermediate/ppanggolin/log.txt
```

Would you be able to advise on why the locus tag is not included in the output? Thanks in advance!

**Comment by axbazin** [comment]
Hi,

This is due to the '>' in the positions which makes it being ignored unless the "--use_pseudo" option is given when running the 'annotate' step. 
This option is not available through the 'all' workflow, so you'll have to build your pangenome using a step-by-step approach to have those genes in.

Adelme

**Comment by ezherman** [comment]
Hi Adelme, Thank you for the quick and clear response!

Cheers,
Ezra
