### ISSUE TITLE
ppanggolin draw --spots all don't create plots for all spots

### ISSUE THREAD

**Issue by IsabelFE** [labgem/PPanGGOLiN#129]
When using `ppanggolin draw --spots all` not all the spots files get created. However if individual spots are listed (like --spots spot_0 or --spots spot_1) the corresponding plots are generated

**Comment by IsabelFE** [comment]
I wrote a workaround:
```
SPOTLIST=$(awk -F'\t' 'NR > 1 { printf "%s%s", (NR > 2 ? "," : ""), $1 } END { print "" }' summarize_spots.tsv)
ppanggolin draw -p pangenome.h5 -o plots --spots $SPOTLIST -f
```
It reads the list of spots from the `summarize_spots.tsv` file and uses that list (SPOTLIST) for `ppanggolin draw --spots`.

The problem is that some spots give an error:

> Traceback (most recent call last):
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/bin/ppanggolin", line 8, in <module>
>     sys.exit(main())
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/ppanggolin/main.py", line 229, in main
>     ppanggolin.figures.launch(args)
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/ppanggolin/figures/drawing.py", line 26, in launch
>     drawSpots(pangenome=pangenome, output=args.output, spot_list=args.spots, disable_bar=args.disable_prog_bar)
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/ppanggolin/figures/draw_spot.py", line 539, in drawSpots
>     disable_bar=disable_bar)
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/ppanggolin/figures/draw_spot.py", line 492, in drawSelectedSpots
>     GeneLists = orderGeneLists(GeneLists, overlapping_match, exact_match, set_size)
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/ppanggolin/figures/draw_spot.py", line 50, in orderGeneLists
>     return rowOrderGeneLists(geneLists)
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/ppanggolin/figures/draw_spot.py", line 70, in rowOrderGeneLists
>     hc = linkage(dist, 'single')
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1060, in linkage
>     n = int(distance.num_obs_y(y))
>   File "/Users/user/miniconda3/envs/PPanGGOLiN/lib/python3.6/site-packages/scipy/spatial/distance.py", line 2394, in num_obs_y
>     raise ValueError("The number of observations cannot be determined on "
> ValueError: The number of observations cannot be determined on an empty distance matrix.

**Comment by axbazin** [comment]
Hello,

Which version of PPanGGOLiN is this with?
The error you get from your workaround looks like a bug fixed in [1.2.105](https://github.com/labgem/PPanGGOLiN/releases/tag/1.2.105) which happened when spots had a single RGP "synteny" (if all RGPs of the spot have identical gene orders).

The 'all' spot should draw all spots with more than one RGP "synteny". If you see that it's not the case feel free to share an example figure, or the pangenome itself so I can have a look more in detail.

Adelme

**Comment by IsabelFE** [comment]
I am using ppanggolin 1.2.74 from bioconda.
For all spots with more than one RGP "synteny", is that the value on the nb_rgp column on the summarize_spots.tsv file? Because those are the ones giving the error. Yesterday I updated my workaround so it looks at this column ($2>1) and only includes the spot on the list if the nb_rgp value is >1:

```
SPOTLIST=$(awk -F'\t' 'NR > 1 && $2 > 1 { printf "%s%s", (NR > 2 ? "," : ""), $1 } END { print "" }' summarize_spots.tsv)
ppanggolin draw -p pangenome.h5 -o plots --spots $SPOTLIST -f
```

With this I get more plots than with the -all option

**Comment by axbazin** [comment]
Upgrading to 1.2.105 should solve this error then.

nb_rgp is the number of RGPs in the spot without looking at if they are different or not. The column 'nb_unique_family_sets' indicates how many different RGPs there are.

Normally, if you did your workaround on spots that have 'nb_unique_family_sets' above 1, it should get the same result that drawing "all" spots.

I actually made a mistake earlier, the bug should arise only if there is a single RGP in the spot. If multiple RGPs but a single 'RGP synteny' the drawing should work. To be frank my memory is not super clear as I fixed this a year ago. But as I said, if you really want everything, you can just upgrade to 1.2.105 and use your work around and it should get you all of the spots no matter what, if that is what you want.

Maybe this 'all' option should just draw all spots at this point, it'd just make more sense and make things simpler.

**Comment by IsabelFE** [comment]
Thanks! I will update to 1.2.105.
Yeah maybe more control on the draw version will be useful, like having a real "all" option and an option for only the ones with more than one RGP "synteny"

**Comment by axbazin** [comment]
Closing as we included those 'all' and 'synteny' keywords with their expected meanings in the latest release !
