### ISSUE TITLE
Ignore genes during clustering

### ISSUE THREAD

**Issue by Czirion** [labgem/PPanGGOLiN#131]
Hello,

I used PPanGGOLiN from gbks to do the whole pipeline and now, after an examination of the pangenome, I want to remove some families (so that they are not considered in the rarefaction, RGP, modules, and spots, for example). What I did, was remove those families from the `gene_families.tsv` file and use that file to run PPanGGOLiN again with the `--clusters` option. 

The problem is that I get this error message: 
`Exception: Some genes (2290) did not have an associated cluster. Either change your cluster file so that each gene has a cluster, or use the --infer_singletons option to infer a cluster for each non-clustered gene.`

I believe that neither of the options provided will behave as I would like to. 
Is there another way to ignore certain families? 

Thank you for the amazing software,

Claudia

**Comment by axbazin** [comment]
Hi,

My apologies but I do not think it is possible to do what you want to do easily.
The best "simple" solution I'd have would be to remove the genes that you want to ignore from the .gbk files.

Adelme
