### ISSUE TITLE
Comparing core genomes

### ISSUE THREAD

**Issue by SamVaGo** [labgem/PPanGGOLiN#136]
Is there a possibility to compare core genomes (or persistent genes) and extract the "difference"?

**Comment by axbazin** [comment]
Hi,

Yes, you can write down the gene families belonging to all partitions with:

`ppanggolin write -p pangenome.h5 --partitions --output MYOUTPUTDIR`

There you find lists for exact core, soft core, persistent, shell, anything you may want.

Then if you sort the files and diff them, you can easily get the difference, e.g.:
`
cat exact_core.txt | sort > sorted_exact_core.txt 
cat persistent.txt | sort > sorted_persistent.txt 

#nb of genes in persistent and not in exact core
diff sorted_exact_core.txt  sorted_persistent.txt | grep -c '>'

#nb of genes in exact core and not in persistent
diff sorted_exact_core.txt  sorted_persistent.txt | grep -c '<'
`
Or do any other kind of comparisons quite easily.

**Comment by axbazin** [comment]
If you meant between pangenomes, you can follow what I've written in this issue: https://github.com/labgem/PPanGGOLiN/issues/68#issuecomment-935782782

**Comment by SamVaGo** [comment]
Hi,

Thank you for the quick response! I would like to compare the core genome of one group of organisms (of one species) and compare them to another group from the same species (but a different lineage) in order to check the difference between the two lineages. 

In essence it is not really the "species core genome" that I would like to compare, but rather the genes that are (almost) always present in one lineage and how they differ from the genes that are "core" to the other lineage. It would be like taking the core genome of the lineage and substract the core genome of the species in order to have the lineage-specific core.

Many thanks!

Best
Sam

**Comment by axbazin** [comment]
I see !
In essence, it's quite similar, with some variations, to my answer in https://github.com/labgem/PPanGGOLiN/issues/68#issuecomment-935782782

You can do it as such:

get all persistent sequences for both pangenomes:
```
ppanggolin fasta --prot_families persistent -p pangenome_1.h5 -o prot_persistent_species_1 
ppanggolin fasta --prot_families persistent -p pangenome_2.h5 -o prot_persistent_species_2
```
Those commands will write a file 'persistent_protein_families.faa' in the output directory provided with -o.
Then, you can compare this file to the other pangenome:
```
ppanggolin align -p  pangenome_1.h5 --proteins prot_persistent_species_1/persistent_protein_families.faa -o align_persistent_pang2_to_pang1
ppanggolin align -p  pangenome_2.h5 --proteins prot_persistent_species_2/persistent_protein_families.faa -o align_persistent_pang1_to_pang2
```
You can provide --identity  and --coverage thresholds for the comparison to 'ppanggolin align', to define depending on how distant your species are I guess

Then, you should get results on what is persistent from one species persistent in the other species, by reading the 'proteins_partition_projection.tsv' file.

It should get you close to what you wish to achieve, if I understood correctly !

**Comment by SamVaGo** [comment]
I think so, many thanks!

**Comment by SamVaGo** [comment]
Is it correct that the code above should start with the .faa file after -S?
I also assume that pangenome1 should be aligned with prot_persistent_species_2/persistent_protein_families.faa?

Thanks again!

**Comment by axbazin** [comment]
I did not understand what you meant by "-S".

Your assumption is correct it seems I wrote it too quickly, sorry!
