### ISSUE TITLE
requirement file

### ISSUE THREAD

**Issue by sletort** [labgem/PPanGGOLiN#14]
when using pip with the requirement file I've got the error:
```bash
$ pip install -r requirements.txt 
ERROR: Invalid requirement: 'tqdm=4.*' (from line 2 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

$ pip --version
pip 19.2.3
```
Do you use this file with pip ? It seems that the syntax is not correct.
I'm using miniconda, it may be a cause.

**Comment by axbazin** [comment]
No I use this file with conda. (conda install -n myenv --file requirements.txt)
Some of the requirements we use are not in pip.
