### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by LongXiang99** [labgem/PPanGGOLiN#155]
Hello,

Thank you for designing this pipeline, which is really easy for non-experts to use. 
I met a problem below(error code):
_Found conflicts! Looking for incompatible packages.Press CTRL-C to abort.This can take several minutes .failed
UnsatisfiableError: The following specifications were found to be incompatible w
ith each other:
-> Available versionsThe following specificaOutput in format: Requested packagetions were found to be incompattble with your system:
feature:/linux-64:: glibc==2.35=0
feature:l@/linux-64:: glibc==2.35=0
ppanggolin -> mafft ->   glibc[version='>=2.17']
Your installed version is: 2.35_
#In fact, when I try to install glibc-2.17, it mentioned that gcc and make too old?
gcc --version11.0   make --version4.3, it should be right. I don't know how to do next?

**Comment by ggautreau** [comment]
Hi @LongXiang99,

It appears that the problem is related to conda. You might find it helpful to read this link: https://github.com/conda/conda/issues/12912

Best,

**Comment by jpjarnoux** [comment]
Hi @LongXiang99
To supplement what @ggautreau said, I recommend that you install PPanGGOLiN in a different environment. This will avoid compatibility problems between packages.
You can use the following command to install PPanGGOLiN in a separate environment. 
`conda create -n ppanggo -c conda-forge -c bioconda ppanggolin`
Let us know if it works.
