### ISSUE TITLE
Missing genes in the projection.tsv files

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#168]
Hello,

I would like to know if what I observe is normal or not: I noticed the number of genes in my GFF files and projection/*.tsv files are not the same. At least for 3 genomes:
genome1 GFF: 6446 genes
genome1 TSV: 6352 genes
genome2 GFF: 6253 genes
genome2 TSV: 6163 genes
genome3 GFF: 6227 genes
genome3 TSV: 6154 genes

Looking forward to your feedback.
Thanks

Have a great day
Cécile Monat

**Comment by axbazin** [comment]
Hi Cécile,

Assuming this is with PPanGGOLiN v1.2.105, and with its default options, this is likely due to the default behavior of not reading pseudogenes. If you wish to change this behavior, you can use the ''--use_pseudo" option of `ppanggolin annotate`

Adelme

**Comment by cmonat** [comment]
Ok, thanks
C.
