### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by seajane** [labgem/PPanGGOLiN#189]
The link to an example yeilds a 404 error: https://github.com/labgem/PPanGGOLiN/blob/master/testingDataset/organisms.fasta.list
<img width="1091" alt="Screenshot 2024-03-11 at 10 28 57 PM" src="https://github.com/labgem/PPanGGOLiN/assets/8787869/a3a8ec01-3c0d-4ae8-a8cd-0b260fd4ef87">

**Comment by seajane** [comment]
This link to the testingDataset is also dead: https://github.com/labgem/PPanGGOLiN/blob/master/testingDataset/organisms.gbff.list
<img width="1091" alt="Screenshot 2024-03-11 at 10 35 30 PM" src="https://github.com/labgem/PPanGGOLiN/assets/8787869/8546ca90-db45-46ca-be1b-579c7a36d73e">

**Comment by axbazin** [comment]
Hi,

Normally all dead links have been updated to their proper current versions in the doc.

Adelme
