### ISSUE TITLE
Extract fasta files

### ISSUE THREAD

**Issue by SamVaGo** [labgem/PPanGGOLiN#191]
Dear

Before the update to version 2.0, it was possible to extract a fasta file of, for example, all persistent genes. It appears that this function has been removed. Is this correct? If so, why was it removed (ie. should I be careful with data in which I used this previously)?

Many thanks
Sam

**Comment by JeanMainguy** [comment]
Hello, 
This option is still available in version 2 with the `fasta` command. 
The following command would write all persistent genes of the pangenome:
```bash
ppanggolin fasta -p pangenome.h5 --genes persistent -o genes/
```
Best, 
Jean

**Comment by SamVaGo** [comment]
My apologies, I had received an error that this was not a functional command. 
I have used GFF files and added the corresponding FASTA files (as mentioned in the manual). Possibly something went wrong there. As I didn't retrieve the function in the manual, I thought it was removed with the latest update. I will try again! 
Thank you for the quick reply!

Best
Sam

**Comment by JeanMainguy** [comment]
In deed the documentation of the `fasta` command seems missing.
We will fix that asap.

**Comment by JeanMainguy** [comment]
The updated documentation is online with the part about the fasta command: https://ppanggolin.readthedocs.io/en/latest/user/writeFasta.html 
Thanks for reporting this missing documentation.

**Comment by axbazin** [comment]
Hi @GuilhemRoyer , actually I don't think it is currently possible with the command line.

I think it is technically possible to do something that would read the HDF5 and write only the sequences from a given gene family in a relatively fast way, though.

That would definitely be a nice improvement making it more practical to use the HDF5 as a storage solution for large genomic data.
