### ISSUE TITLE
Does PPanGGOLiN provides functional annotation?

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#194]
Hi,

just would like to confirm something, PPanGGOLiN enables structural annotation, but does it also include a functional annotation step? If so, which software is used?
Many thanks
Have a great day

C.

**Comment by cmonat** [comment]
Ok, thanks a lot!
C.

**Comment by jpjarnoux** [comment]
Hi, 
Please note that you can now add metadata to all pangenome elements.
For example, you can write the fasta sequences of gene families, do the functional annotation with another tool, and write the result to your pangenome and output files. 
It's not your question, but this new feature could help. 
You'll find more information in our documentation: https://ppanggolin.readthedocs.io/en/latest/user/metadata.html.
