### ISSUE TITLE
Annotation with user-provided CDS fasta sequences

### ISSUE THREAD

**Issue by seajane** [labgem/PPanGGOLiN#197]
I am trying to create a PPanGGOLiN pangenome using annotations from another source. I have gff3 files and matched fasta. I am running version ppanggolin 2.0.2. I used this command:  `ppanggolin annotate --anno gffdf.list --fasta eggfast.list`. I received this error 
<img width="963" alt="Screenshot 2024-03-19 at 11 22 42 AM" src="https://github.com/labgem/PPanGGOLiN/assets/8787869/b8da78a3-dd7c-4962-9e28-b8a0d46b1daa">

**Comment by seajane** [comment]
Now that I see the whole error, I believe one problem lies in fasta type. PPanGGOLiN is expecting DNA files (I assume, from the 'get_dna_Sequence' and 'reverse complement' function that failed.) Is there anyway to use AA sequences?

**Comment by seajane** [comment]
I converted all my AA sequences using both degenerate bases and a random trinucleotide code for each amino acid. The final error above is the same on the bottom, the initial error has switched to ```
Traceback (most recent call last):
  File "/Users/hbouzek/opt/anaconda3/envs/ppgg-new2/lib/python3.10/site-packages/ppanggolin/annotate/annotate.py", line 578, in get_gene_sequences_from_fastas
    gene.add_sequence(get_dna_sequence(fasta_dict[org][contig.name], gene))
KeyError: 'NZ_NQOP01000002.1_1'
```

**Comment by axbazin** [comment]
Hi,

So I'm not quite sure what is happenning with the code, but ppanggolin deals with genomic dna fasta files and nothing else. It does not expect to work with AA or CDS fasta files.

With what you want to do, if you really want to use PPanGGOLiN I'd recommend to use the path of providing your own clustering, using this option: https://ppanggolin.readthedocs.io/en/latest/user/PangenomeAnalyses/pangenomeAnalyses.html#providing-your-gene-families

Along with the gff3 files that you are already using.
If you are looking for a tool for the clustering, PPanGGOLiN uses MMseqs2 internally, so you can probably have a go with that.

I agree that in your case where gff3 files are provided things could work with AA or CDS fasta sequences in theory, but we have not gone this path.

Adelme
