### ISSUE TITLE
End of my hacktober

### ISSUE THREAD

**Issue by sletort** [labgem/PPanGGOLiN#21]
Hi,

With my last PR ends my contrib for this hacktoberfest (I already won my t-shirt !)
I'd like to encourage you to continue this interesting project.  
I also want to share the impression that the implementation is disturbing, with the edge that point to gene which point to the edge for example or the gene that can belong to an organism which has no gene. But once I said that, I must also admit that nothing obvious came to my mind to correct it. I suppose as the project will mature, things will be reorganized.

good luck.

**Comment by axbazin** [comment]
Hi,

Congrats for your t-shirt ;)

Thanks a lot for your comments, I do agree that some things are in clear need of improvement code-wise. And thank you for the unit tests that you added, I like the way this works I'll try add some for the different modules in the future.
