### ISSUE TITLE
Gene family count matrix related with representative  gene family . 

### ISSUE THREAD

**Issue by aababc1** [labgem/PPanGGOLiN#217]
Thank you for creating such a great tool. 
I have one question, your tool doesn't seem to generate the gene count matrix directly. If I want to generate a count table in addition to gene presence absence, I wonder if I need to manually generate a count table using the gene_families.tsv information.
Or is there some other command that supports this functionality in ppanggolin?
Thank you in advance for your answer.

**Comment by axbazin** [comment]
Thank you for your kind words!

Indeed I do not think we have such a file among the possible outputs.
The closest would probably be the "matrix.csv" file (see [this](https://ppanggolin.readthedocs.io/en/latest/user/PangenomeAnalyses/pangenomeAnalyses.html#matrix-file) which has all the information you want, but has the list of genes rather than the raw count itself. Transforming this file may be your easiest way out.

Otherwise, using the gene_families.tsv file along with one of the file that links genes to genomes (e.g., the gff or the [genes annotation table](https://ppanggolin.readthedocs.io/en/latest/user/writeGenomes.html#genes-table-with-pangenome-annotations) files) is a good solution too.

Adelme

**Comment by aababc1** [comment]
Thank you for your prompt response!

I have two more question . 

As your suggestion,I generated custom script for that. The number of the all genes in  result file matched with the number of  lines in gene_families.tsv . I attached it and please tell me if there could be source of error. 
 
First one is, ppanggolin represent F in third column in  gene_families.tsv file that are fragmented.  I included them for the analysis. I thought  the fragmented  gene sequences could be annotated functionally and it could be utilized for downstream anlaysis. I wonder your opinion about fragmented genes information inclusion in downstream analysis.  

Second one is about  gene families threshold. In the paper,coverage 80 % identity 80% was utilized for gene family construction. This are frequently used for gene family clustering, but I have question about adjusting the coverage and identity for species level in microbial comparative genomic analysis. If the species are different, users should choose different clustering criteria , or just default values could be utilized for analysis? And if someone lowering the identity to 50%,  there could  be severe bias  introduced in downstream analysis based on pangenome function annotation based on pangenome reference sequences? 

Thank you very much Bazin

`import os
import re
import argparse
from collections import defaultdict

# Parse command-line arguments
parser = argparse.ArgumentParser(description='Generate gene count matrix from gff files and gene_families.tsv')
parser.add_argument('input_dir', help='Input directory containing gff folder and gene_families.tsv')
args = parser.parse_args()

# Extract genome ID from gff files and create genome_id_linking file
genome_id_linking = {}
gff_dir = os.path.join(args.input_dir, 'gff')  
for gff_file in os.listdir(gff_dir):
    with open(os.path.join(gff_dir, gff_file), "r") as f:
        for line in f:
            if "\tCDS\t" in line:
                match = re.search(r"ID=(.{8})_\d{5}", line)
                if match:
                    genome_id = match.group(1)
                    genome_id_linking[genome_id] = os.path.splitext(gff_file)[0]
                    break

with open(os.path.join(args.input_dir, "genome_id_linking.tsv"), "w") as f:
    for genome_id, gff_prefix in genome_id_linking.items():
        f.write(f"{gff_prefix}\t{genome_id}\n")

# Extract 1st and 2nd tabs from gene_families.tsv and convert genome ID
gene_families = defaultdict(lambda: defaultdict(int))
gene_families_file = os.path.join(args.input_dir, "gene_families.tsv")  
with open(gene_families_file, "r") as f:
    for line in f:
        gene_family_id, gene_id = line.strip().split("\t")[:2]
        genome_id_prefix = gene_id.split("_")[0]
        genome_id = genome_id_linking.get(genome_id_prefix, genome_id_prefix)
        gene_families[gene_family_id][genome_id] += 1

# Generate gene_count_matrix.tsv file
gene_family_ids = sorted(gene_families.keys())
genome_ids = sorted(set(genome_id_linking.values()))

output_file = os.path.join(args.input_dir, "gene_count_matrix.tsv") 
with open(output_file, "w") as f:
    f.write("Gene\t" + "\t".join(genome_ids) + "\n")
    for gene_family_id in gene_family_ids:
        counts = [str(gene_families[gene_family_id][genome_id]) for genome_id in genome_ids]
        f.write(gene_family_id + "\t" + "\t".join(counts) + "\n")
`

**Comment by axbazin** [comment]
Your script looks fine for me, it does seem to be doing what you want.

About the fragmented genes, it depends on the "downstream analysis" and the biological question. From the technical point of view, if you are annotating genes independently from their gene families, then I think it is fine. If you are doing functional annotations at the scope of gene families, I'd remove them as they may not be able to realize the "function" that they would be annotated with.

For the question of gene families threshold, indeed I'd recommend to lower the identity threshold for clustering. If they are "close" sister species (e.g. Neisseria meningitidis and Neisseria gonorrhoeae) 80% is fine, but in general lowering it is better. However you are correct, it may generate a strong bias if you are annotating your gene families, as some paralogs with different functions may be annotated exactly the same way, in that case. That will only be true for some families though. It's a balance to have between wrongly clustered paralogs and wrongly splitted orthologs, you can adjust the threshold depending on what's important to your own analysis/biological question.

In my opinion, while annotating gene families is "practical" and much faster,  annotating genes directly is still best if you want to avoid mistakes as much as possible.

Have a nice day!
Adelme

**Comment by aababc1** [comment]
Thank you so much for your very detail explanation . 

I asked the gene family clustering threshold and fragmented gene families because I am handling fragmented genomes such as MAG. As you commented, annotate genomes individually will show best accuracy I think.  I will test some things  based on you advice.  My questions are all resolved. Thank you once again.

Have a nice day!
