### ISSUE TITLE
RGP borders not in regions_of_plasticity.tsv

### ISSUE THREAD

**Issue by KerrinSteensen** [labgem/PPanGGOLiN#218]
Hi, 

I was using ppanggolin 1.2.105 before, and got the "start" and "stop" contig borders of the regions_of_plasticity file. 
With the new version (2.0.5) I only get the "start" and "stop" CDS of the borders. 

example old version:
region  organism        contig  start   stop    genes   contigBorder    wholeContig
strainX_contig001_RGP_14  strainX   strainX_contig001 **74974   86546**   8       False   False

example new version:
region  genome  contig  start   stop    genes   contigBorder    wholeContig
strainX_contig0004_RGP_0      strainX       strainX_contig0004    **strainX_CDS_0254      strainX_CDS_0281**      28      True    True

Is there any way I can get the nucleotide borders (like in the old version)?
The command I am using is :
ppanggolin panrgp --fasta fastalist.txt -f --output $HOMEDIR/results/1_ppanggolin/

Thank you!

**Comment by axbazin** [comment]
Hi,

Indeed, I see where and when this change happened and I'm not 100% sure the change was voluntary, I will verify that.

In the meantime, there is no "easy" way to get that file the way you want it, but you can retrieve the info of gene starts and gene stops in any of the "genome" annotations file like [gff](https://ppanggolin.readthedocs.io/en/latest/user/writeGenomes.html#gff-file) or [gene table](https://ppanggolin.readthedocs.io/en/latest/user/writeGenomes.html#genes-table-with-pangenome-annotations), so it's definitely doable to write in the 'older' format with a small script.

I'll come back to this issue with the answer on whether this change was voluntary or if we'll be rolling back in futur versions.

Have a nice day,
Adelme

**Comment by KerrinSteensen** [comment]
Hi Adelme, 

thanks so much for your quick response and for the suggestions to find a workaround! 
I can already see that you started working on that issue and am looking forward to the next version of ppanggolin! 

Have a good day!
Kerrin

**Comment by JeanMainguy** [comment]
The fix for this issue has been released in v2.1.0.

**Comment by KerrinSteensen** [comment]
That's great. Thank you!
