### ISSUE TITLE
Getting errors with bad ORGANISM_FASTA_LIST

### ISSUE THREAD

**Issue by vinisalazar** [labgem/PPanGGOLiN#22]
Hi,

I was having some troubles running the workflow and graph commands.

After removing spaces from my ORGANISM_FASTA_LIST file used as input, the workflow worked smoothly.

I thought maybe people would benefit if that was somehow explained in the README, as I spent quite some time trying to debug.

Thank you for any assistance you can provide.

V

**Comment by vinisalazar** [comment]
Addressed a suggestion with #23

**Comment by ggautreau** [comment]
Hi @vinisalazar,

Sorry for this issue, thank you for reporting it.

You are completely right, we forgot to mention that.

I accept your pull request.

Bye.
