### ISSUE TITLE
ppanggolin msa --partition core

### ISSUE THREAD

**Issue by lfdelzam** [labgem/PPanGGOLiN#231]
Thank you for developing such a great program! I've been using ppanggolin msa and it's been helpful. Here is the command I've been working with:

ppanggolin msa -p Pangenome_graph/pangenome.h5 --partition core --source dna -o Pangenome_graph/MSA --phylo -c 20 -f

The documentation mentions: "By default it will write the strict 'core' (genes that are present in absolutely all genomes) and remove any duplicated genes."

I'm curious to learn more about how this workflow operates, especially regarding the removal of duplicated genes. Could you please provide more details on what exactly this entails? Specifically, does the program select one copy of the duplicated genes or does it only use single copy genes?

Thanks in advance

**Comment by lfdelzam** [comment]
So, the non single copy genes within the family or the entire family of genes are removed?

**Comment by JeanMainguy** [comment]
It is the non single copy genes within the family that are removed.

**Comment by fwhelan** [comment]
If I could jump on this, when the `--phylo` flag is used, how are the gene family MSAs concatenated into a core gene alignment? Specifically, is this done in a codon aware manner?

Thank you! Really appreciate how well coded and easy to use ppanggolin is!

**Comment by axbazin** [comment]
Hi,

It is not. The set of families selected (core, in your case) for the alignment is concatenated by simply iterating over those families. Their order is random.

I'm not particularly knowledged on the concatenated core gene alignment topic. It is one of those functionnality coded to help a user, and that quite a few people ended up using. If you think it's important to do it the way you describe it, feel free to send over a paper or equivalent describing it, and if possible we can definitely consider doing it a better way in a futur release!

Thank you for your kind words!

Adelme

**Comment by fwhelan** [comment]
Wow you're quick! :)

Thanks! I also don't particularly know a lot about this topic. In short, I have used a few different pangenome tools on a set of very closely related genomes and am getting very different core gene tree topologies, so just trying to understand the potential causes. I completely understand that different tools make different choices, but given that there is little gene gain/loss and ani scores >90%, I thought the pipelines would align a bit more.

This is very helpful to know, though, thank you!
