### ISSUE TITLE
Lowercase FastA

### ISSUE THREAD

**Issue by BioSina** [labgem/PPanGGOLiN#24]
Currently PPanggolin does not work on FastA input with lowercase sequence. This should be a quick fix, though.

It fails on reverse_complement (maybe other places, but this fails first).

**Comment by axbazin** [comment]
Hello,

I did reproduce the bug, I'll push a fix to the github repo later today.

Once it is done if you want to reinstall ppanggolin with the fix and if you installed it previously with conda, you can clone the repo, go to its root and, with the conda environment activated run : 

`pip install .`

It should remove the current version of PPanGGOLiN and replace it with the new one, and everything should work as expected.

**Comment by axbazin** [comment]
The latest commits should fix your problem.

**Comment by BioSina** [comment]
Did you push this to conda? Because your fix using pip install will not work as expected on the system I work on.

**Comment by axbazin** [comment]
I made the release, the bioconda version should update within a few hours/days.

**Comment by axbazin** [comment]
The bioconda version is updated.
