### ISSUE TITLE
Add gene name info in the Tile Plot

### ISSUE THREAD

**Issue by JeanMainguy** [labgem/PPanGGOLiN#251]
As suggested in issue #53 by @fwhelan, it would be helpful to display the most common gene name found in each family on the tile plot to aid in interpretation.

To implement this, we can add the most common gene name to the hover info for each cell in the tile plot. 

In addition, the tile plot can be further enhanced by:
- Including metadata information associated with the families in the hover info, along with the most common gene name.
- Removing axis labels when there are too many families or genomes, as they are anyway unreadable.

**Comment by fwhelan** [comment]
Thanks, JeanMainguy!

**Comment by JeanMainguy** [comment]
Hello,
The tile plotting has been improved in PR #277, released in version 2.1.2, and now includes the gene name in the hover info when available.
