### ISSUE TITLE
conda installs old version

### ISSUE THREAD

**Issue by IsabelFE** [labgem/PPanGGOLiN#260]
I tried to install using `conda install bioconda::ppanggolin` and version ppanggolin 1.2.74 was installed. 

I am also not able to install the new version using the install from source instructions

**Comment by JeanMainguy** [comment]
Hi,

To install a specific version of `ppanggolin` with conda, you can use the command:

```bash
conda install bioconda::ppanggolin=2.1.0
```

If conda encounters issues installing the specified version, it will typically provide information about the problem. One possible cause for installation issues could be incompatibilities with other software packages in your current conda environment that conflict with the lastest version of `ppanggolin`.

We recommend installing `ppanggolin` in a dedicated conda environment to avoid such conflicts. You can create a new environment and install the latest version of `ppanggolin` using the following commands:


```bash
conda create -n ppanggo -c defaults -c conda-forge -c bioconda ppanggolin
conda activate ppanggo
```

This should install the lastest version of ppanggolin, however you can specify a specific version during the environment creation:

```bash
conda create -n ppanggo -c defaults -c conda-forge -c bioconda ppanggolin=2.1.0
```

Hope this helps!

Best regards,

**Comment by IsabelFE** [comment]
Thanks!. Both ways installed the last version. I was initially creating the empty environment first and then doing `conda install bioconda::ppanggolin`, and that defaults to a previous version.
