### ISSUE TITLE
Update MMseqs command

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#27]
On the createdb of MMseqs2 (`ppanggolin/cluster/cluster.py`) last realease the option `--dont-shuffle` is replace by `--shuffle`

**Comment by axbazin** [comment]
Indeed, thank you for pointing that out, I'll fix this soon

**Comment by axbazin** [comment]
The last commit should solve the problem, I just removed the option and rely on mmseqs2's default value (which is now --shuffle true apparently)

**Comment by Nilad** [comment]
Tested and worked.

Thanks for the update.
