### ISSUE TITLE
Add function or process to produce a MSA file

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#28]
With the evidence reference of PPanGGOLiN with `Roary`, how produce one, instead of the, most important file in roary ,the MSA file, with PPanGGOLiN ?

It would be nice to have a kind of function that allow to choose with which "pangenomes genes set" defines in PPanGGOLiN, a MSA file can be produce. Example: I want to have a MSA with the persitent genes or i want to have a MSA with the shell genes.

**Comment by axbazin** [comment]
This could be useful for some applications, and it is probably not too difficult to do in the current state of the code.

As of now, you can extract the gene sequences for the whole pangenome, and the gene family to gene association using :
`ppanggolin write -p pangenome.h5 --all_genes --families_tsv -o OUTPUTDIR`
It will provide two files:
-  "gene_families.tsv" with the gene family in the first column and gene IDs in the second column.
- "all_genes.fna" with all of the nucleotide gene sequences.

With some scripting it is possible to then get all the gene sequences for each gene family and then run your favorite multiple sequence aligner on it.

I agree that doing this, for now, is not very practical. We will look into doing this process automatically in ppanggolin in the future.
