### ISSUE TITLE
Formula for calculating chao could be wrong

### ISSUE THREAD

**Issue by luenna** [labgem/PPanGGOLiN#281]
https://github.com/labgem/PPanGGOLiN/blob/83c7d75d2b76df6ba2de8d855cdc281e108e5bba/ppanggolin/figures/ucurve.py#L42

It looks like the chao is using gene families that appear in zero genomes as F1 and gene families that appear in 1 genome as F2, when it should be 1 and 2. The way it currently is the chao returns always the number of gene families, since (count[0]["pangenome"] ^ 2) will always be 0, thus turning the whole latter part zero.

**Comment by axbazin** [comment]
Hi,

Thank you for reporting this, the fix will be in the next release !

Adelme

**Comment by JeanMainguy** [comment]
This has been fixed and released in version 2.2.0. 
Thanks again for reporting this.
