### ISSUE TITLE
gbff.gz vs gbff only

### ISSUE THREAD

**Issue by survivor77** [labgem/PPanGGOLiN#289]
Hello there,

Thank you for this tool. I was able to run the tool successfully with 5 genomes and annotation files. All these had the suffix .gz at the end. 

However, I plan to run the tool on more that 500 strains. The files that I download from the NCBI datasets website have no .gz. I tried running the tool without the .gz suffix for the annotation files and the program gave an error that the files should have a .gz suffix. 

Is there a workaround for the next analysis without .gz suffixes? Thanks and apologies if this was asked earlier.

**Comment by axbazin** [comment]
Hi,

Apologies for the delay. To answer you, normally the files can be given either compressed (with .gz) or not, and it should work the same way.

Adelme

**Comment by survivor77** [comment]
No problem. I got the problem solved and ppanggolin worked like a charm. As you mentioned, it should work with either file format, and it did. Thank you!
