### ISSUE TITLE
Doubt: Unique genes

### ISSUE THREAD

**Issue by fmalmeida** [labgem/PPanGGOLiN#31]
Hi, 

Thank you for such a cool software.
I have recently built a pangenome for 300 genomes and it runs nicely.

However I wonder if it is possible to query the pangenome to discover genes that are present uniquely in one genome.

Additionally, is it possible to create a gene absence/presence matrix for a single genome based on the pangenome's gene content?

Thank you

**Comment by axbazin** [comment]
Hello, 

I see that you closed the issue, did you find what you wanted?

**Comment by fmalmeida** [comment]
Yes, I have found it out. Sorry.

**Comment by axbazin** [comment]
No problem! I'm glad that you found what you wanted. Do not hesitate if you encounter any other issue :)
