### ISSUE TITLE
about plastic regions.tsv

### ISSUE THREAD

**Issue by hansmaelke** [labgem/PPanGGOLiN#32]
Regards.
first of all thanks for ppanggolin
I have a question about the plastic_regions.tsv file. What does mean "true or false" in columns contigBorder and wholeContig

I searched the documentation and found nothing about it and I am not an expert in this area.

I thank you in advance for your help

**Comment by axbazin** [comment]
Hello,

Thank you for your comment !

If "contigBorder" is true, it indicates that the region of plasticity ends (or starts) on a contig border, so it may only be partial.
If "wholeContig" is true, it means that the RGP is on the entire contig, so it both ends and starts on a contig border.

They are not at all terms that are used in the field, just names we came up with for those columns.

If something is unclear, do not hesitate to ask questions again :)
