### ISSUE TITLE
idea to improve use of PPanGGOLiN on MAGs

### ISSUE THREAD

**Issue by taylorreiter** [labgem/PPanGGOLiN#35]
In the PPanGGOLiN publication, the discussion on MAGs notes that incompleteness may cause problems for analysis. Would it be possible to support a count matrix for genes as input to PPanGGOLiN? The count matrix would be composed of genes x samples, and contain either presence/absence or abundance information for each gene. 
I think this input could be a useful way to combat MAG incompleteness.

MAGs are usually incomplete for multiple reasons. Metagenome binners have a difficult time binning contigs ~<2500 base pairs, however many contigs are shorter than this. Assemblers break when they encounter low sequencing coverage, complex regions with a lot of variation, or a lot of sequencing errors, and breaks in assemblies cause short, difficult-to-bin contigs. In the context of pangenomes, it is difficult to know whether a MAG is missing a gene or whether the gene didn't assemble/bin.

One way to combat this would be to use a pangenome gene catalogue. For a group of input MAGs/genomes, the user could use a tool such as CD-HIT to cluster all gene sequences e.g. at 95% similarity, thereby creating a reference set of genes in a pangenome. The user could then map (stringently) all reads from each metagenome sample against the reference set of genes, and generate counts for each gene in each metagenome. This would create a presence/absence (or abundance) matrix for each sample. Instead of relying on de novo assembly and binning, genes could be detected based on mapping.

I think this would improve "completeness" of MAG observations, so long as the reference set of genes in the pangenome was relatively complete. Both Pasolli and a different publication focused on the vaginal microbiome (https://www.nature.com/articles/s41467-020-14677-3#Sec20) showed that while not many things de novo assemble and bin from a single sample, most reads map to de novo assemblies when many assemblies used -- e.g. we don't capture all variation within a single sample, but if we combine variation from all samples, we do a pretty good job of capturing most of it.

**Comment by axbazin** [comment]
Indeed it would be quite interesting, and it would most likely be possible to support a count matrix as input, in theory.

I think @ggautreau  was trying to do something akin to this at the end of his thesis but had to give up due to the lack of time.
