### ISSUE TITLE
Statistics PPanGGolin

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#36]
Hi,

Is it possible to have a small statistic file (like "summary_statistics.txt" from roary) or a command to extract this information from the `.h5` file ?

Bon courage =)

**Comment by ggautreau** [comment]
Hi @Nilad ,

Yes, it is possible using the following command:

`panggolin info -p pangenome.h5 --content`

Merci ;)

**Comment by Nilad** [comment]
Perfect ! Thanks =)
