### ISSUE TITLE
Option to extract the RGPs

### ISSUE THREAD

**Issue by genomesandMGEs** [labgem/PPanGGOLiN#38]
Hey guys,

It would be perfect if you could provide the option to extract the RGPs. From what I understood, right now panrgp provides the coordinates for the start and stop, but on option to extract the delimited regions.
This tool looks quite interesting so far, good work!

**Comment by axbazin** [comment]
Thank you !
Yes panRGP provides the start and stop position of the regions on their sequence.

Do you mean the delimited regions as in something like a fasta file?

**Comment by genomesandMGEs** [comment]
Yes, exactly. A fasta file comprising the nucleotide sequence from the start until the stop position. An option to extract the protein sequences encoded within these regions could also be possible.

**Comment by axbazin** [comment]
Indeed that could be quite practical.

It is not implemented currently.

This is definitely easily achievable for the protein sequences with the current code. 
For obtaining the nucleotide sequence of the whole region, maybe the input files list used to build the pangenome might be needed again, since we do not store the entire genomes in the h5 file.

I'll give some thoughts to this and see if we can incorporate it in ppanggolin, or eventually in a helper script

**Comment by axbazin** [comment]
Hello,

The version on github that I pushed earlier on the master branch implements a way for you to extract the regions nucleotide sequences.

You'll need to replace the conda version (assuming you installed ppanggolin with conda) with the current github one.

The command to write the region's sequences would be:

`ppanggolin fasta --pangenome pangenome.h5 --regions all --fasta yourgenomes.list --output MYOUTPUTDIR` if you used the --fasta options or 
`ppanggolin fasta --pangenome pangenome.h5 --regions all --anno yourgenomesAnnotations.list --output MYOUTPUTDIR` if you used the --anno option to build your pangenome.

you can also write the gene nucleotide sequences in RGPs as such:

`ppanggolin fasta --pangenome pangenome.h5 --genes rgp --fasta yourgenomes.list --output MYOUTPUTDIR`

If sequences are in the pangenome, but that is normally the case unless you built the pangenome by providing a cluster file yourself.

I've ran it on some test datasets and it seemed to work well, if you try it please tell me if it worked !

**Comment by genomesandMGEs** [comment]
Thanks for taking the time to look into this, sounds cool!
In the meantime, I decided to use bedtools to extract the RGPs. I think using bedtools could also help with extracting the regions, without having the replace the ppanggolin version. What's your opinion on this?

**Comment by axbazin** [comment]
bedtools is a good idea actually, whichever works for you is fine for me !

**Comment by axbazin** [comment]
Hello, Since the feature you were proposing was added in commit bf677fc, i'll close this issue, however if you have any comment or questions on this topic feel free to re-open it
