### ISSUE TITLE
Hacktober -> more unit tests

### ISSUE THREAD

**Issue by sletort** [labgem/PPanGGOLiN#39]
Hello,
Hacktober brings me back to your project. :)  

As proposed, in the "Ideas & improvements", I'll make PR to update unit tests and have a better coverage.

**Comment by axbazin** [comment]
Hello,
Thank you in advance then :) 
As I recall I think the 'spot' class (which did not exist last october I believe ?) is the only base class missing tests on master atm, but I might be wrong
Any changes will be tested by github actions now, however I don't really know how that goes with PRs

**Comment by axbazin** [comment]
#41 was the contribution related to this issue.
