### ISSUE TITLE
missing annotations in graph

### ISSUE THREAD

**Issue by jdakota1305** [labgem/PPanGGOLiN#42]
Hi All,

New user of PPanGGOLiN. Really great work! However, I am having some issues with using the --anno workflow. I provided a list of .gbk files that were annotated using ncbi, but the graph only displayed the generic CDS_xx. 

Seems that the annotations I provided were not considered. Is prokka the only annotator that works?

**Comment by axbazin** [comment]
Hi !
Normally all kind of annotations work as long as the format .gbk is followed, i've used annotations from different databases or different annotation tools.

I've had troubles with the identifiers used by the databases/tools though, as they are sometimes not unique (in ncbi genbank notably), but normally we save the ids used in the .gbk file and report them in some of the output files.

If you used the --anno options, your annotations were used, however you are seeing some "internal" unique identifier and not the identifiers from your files.

Which file exactly  were you looking at for the graph ?

If it has been well read, the identifier used in your .gbk file is reported in the .json, in the .gexf, and if the projection files that you can get using: `ppanggolin write -p pangenome.h5 --projection` (it writes one file for each genome)

if you cannot find your identifiers in those files, can you send me one of the files you used so I can test it ?
