### ISSUE TITLE
Unable to Render Hotspots--Running on WSL

### ISSUE THREAD

**Issue by jdakota1305** [labgem/PPanGGOLiN#43]
Hi All,

I am currently trying to use PPanGGOLiN's draw_hotspots subcommand, but am getting no result in my output. I would expect there to be some result on the set of genomes I am using, but am also wondering if there are any known issues with running PPanGGOLiN on Windows via Windows Subsystem for Linux(WSL) and an Ubuntu distribution? 

Essentially, I am just curious if this is a real result or the result of using PPanGGOLiN via WSL.

**Comment by axbazin** [comment]
Hi,
I've never tried nor heard about anyone try to install PPanGGOLiN on WSL to be honest, so I'm not aware of the potential problems you might run into.
Seeing the CI workflow the option should work well, however I've had troubled with this option from time to time, so I will check that everything does work properly with the current version, and get back to you.

I don't expect it to be a real result, I've never seen a set of genome without a single hotspot, however WSL might not be the cause if PPanGGOLiN did not raise any error in the process.

**Comment by axbazin** [comment]
Hello,

So as I said a few days ago I ran some tests and checked the code.

It is possible for you to not get any results drawn with the --draw_hotspots options, if in the 'summarize_spots.tsv' file, none of the spots have the column 'nb_unique_family_sets' above 2. In that case nothing will be drawn but PPanGGOLiN will still finish normally. We require at least 3 different set of families ( 3 genomic islands that differ in terms of gene content, so to say) for the spots to be drawn.

I will add some warnings in the code if that ever happens, to inform the user. It is definitely not clear as it is at the moment.

Can you please confirm that this is your case ? If not there might be an actual problem

**Comment by jdakota1305** [comment]
Hello,

For this particular case, when I run rgp, I do not even get a  'summarize_spots.tsv' file. I have successfully created this file and generated hotspots using a different set of genomes, so it appears to be an issue with this particular dataset. 

Would it be helpful for me to provide one of the sequence files?

**Comment by axbazin** [comment]
Alright, then no spots were detected, those files are written only when at least one spot is detected.

This is quite unusual, as even for Chlamydia trachomatis, which is an obligate intracellular parasite with barely any gene flow, there is a detected spot.

If you have families that are classified in all three partitions (persistent, shell, cloud, seen from `ppanggolin info -p pangenome.h5 --content`), it should be good and is likely an actual result.

I will add a message in the log if that happens as well.

**Comment by axbazin** [comment]
Hello, 

Did you have only circular genomes in your dataset ? It turns out that I just encountered the same problem on a dataset where I expected to find multiple spots. The dataset consisted only of circular genomes.

It turns out that there was indeed a bug in those specific conditions, where the border extraction was not done at all (and so spots could not be found).

If that is the case sorry for the inconvenience, I'll fix this in the master branch soon however that might take some time to get updated on bioconda.

**Comment by axbazin** [comment]
The latest release should fix this. If not, please do not hesitate to reopen ! :)
