### ISSUE TITLE
get annotation?

### ISSUE THREAD

**Issue by csavin75** [labgem/PPanGGOLiN#45]
Hi,

Is there a way to recover the annotation files (like .gff) after the annotation done by ppagnggolin pipeline?

By the way, very nice, powerful and useful tool you developed!!

Cyril

**Comment by axbazin** [comment]
Hi,
Thank you !

There is an unpractical way to do it at the moment, using the following command:

` ppanggolin write -p pangenome.h5 --projection --output MYOUTPUTDIR`

It will write tab-separated files, one file per genome, that indicates the genes, their positions and their associated partition, and some other metrics (details for each column are here: [projection wiki](https://github.com/labgem/PPanGGOLiN/wiki/Outputs#projection) )

A gff file would be definitely much more practical, it is on the todo list

Adelme
