### ISSUE TITLE
Minimum and maximum number of organism for rarefaction curve

### ISSUE THREAD

**Issue by zakisaati** [labgem/PPanGGOLiN#50]
Hi there,

I am not sure if I totally understand the processes of partitions and sampling made to build the rarefaction curves through the "ppanggolin rarefaction" command. By defect, the --min is set to 1 and --max is 100. I am running a dataset with >3000 genomes from many different species from the same genus. Therefore, I am not sure whether i should increase the --max value up tu the number of genomes in my analysis. Typically, I found that these curves have so many genomes in the X axis as the number of genomes in the analyses. However, since the processes made by ppanggolin are quite different, I am not sure about that. Morevoer, when running this command with deffault settings, the log says:

2021-01-26 06:36:57 rarefaction.py:l285 INFO	Done sampling organisms in the pangenome, there are 2970 samples

Why 2970 samples? I have almost 3400 genomes in the dataset...
Could anyone advise me in this sense, please?

Thank you in advance

**Comment by axbazin** [comment]
Hi,

The --max is limited to 100 to limit to computational load when computing the rarefaction curve. You can increase this limit up to your number of genomes, but that will mean a lot more computational resources for the end points for the number of genomes that you have.

The number of samples correspond to the number of 'groups of genomes' made to draw the rarefaction curve. To have the rarefaction curve computed in a doable time, we don't compute all possible combinations of genomes (as it would quickly represent intractable computations) but instead create multiple samples that should be representative of your pangenome. Then PPanGGOLiN runs its partitionning algorithm on each sample separately.

There is a 3rd parameter that will impact the number of samples made which is the --depth parameter. This correspond to the number of samples (groups of genomes) that will be made at each point along the X axis. By default, it is 30, so from 1 to 100 this represents 99 'number of genomes' * 30 depths = 2970 samples.

I hope that this answers your questions, if I was not clear enough or if you have other questions please do not hesitate !

Adelme

**Comment by zakisaati** [comment]
Ok, no I understand. Thank you very much for your response :)
