### ISSUE TITLE
gbk file is not work!

### ISSUE THREAD

**Issue by sunnycqcn** [labgem/PPanGGOLiN#51]
Hello,
I  tried using gbff file, it work well. But when I use gbk file, it did not work.
Thanks,
Fuyou

**Comment by axbazin** [comment]
Hello,

I'm going to need more details to be able to help you.
Can you send me the gbk file which did not work, or tell me where to download it so I can check where the problem is ?

Adelme

**Comment by sunnycqcn** [comment]
Hello,
My gbk file is generated by software funannotate. One gene format is like:
`LOCUS       lm_SuperContig_0_v2  4258568 bp    DNA     linear       19-JAN-2021
DEFINITION  JN3 strain JN3 isolate JN3.
ACCESSION
VERSION
KEYWORDS    .
SOURCE      JN3
  ORGANISM  JN3
            Unclassified.
REFERENCE   1  (bases 1 to 4258568)
  AUTHORS   Palmer,J.M.
  TITLE     Direct Submission
  JOURNAL   Submitted (19-JAN-2021) CFMR, USDA Forest Service, 1 Gifford
            Pinchot Drive, Madison, WI 53726, USA
COMMENT     'Annotated using 1.8.4'.
FEATURES             Location/Qualifiers
     source          1..4258568
                     /organism="JN3"
                     /mol_type="genomic DNA"
                     /strain="JN3"
                     /isolate="JN3"
     gap             13692..18727
                     /estimated_length=5036
     gap             38988..39137
                     /estimated_length=150
     gap             51547..51950
                     /estimated_length=404
     gap             54030..54179
                     /estimated_length=150
     gap             92044..92610
                     /estimated_length=567
     gap             93724..98517
                     /estimated_length=4794
     gene            complement(134783..135262)
                     /gene="jgi.p|Lepmu1|1"
                     /locus_tag="gene_1"
     mRNA            complement(134783..135262)
                     /gene="jgi.p|Lepmu1|1"
                     /locus_tag="gene_1"
                     /product="hypothetical protein"
     CDS             complement(134783..135262)
                     /gene="jgi.p|Lepmu1|1"
                     /locus_tag="gene_1"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:gene_1-T1"
                     /translation="MSKKKSHTLKEANKSSRMYPSLHQEVTNAVSKHISLLVFHAEDS
                     AEGVNEEYSTYARGVFRCYNANCSTRSWSSGKVTLLIRKYRDGTYNAVVFKQRCEECK
                     RLGKLKLDETSYTDRVTYRLLKWAGVAQAQPYHGSKTTPPHKSHLCEGCKRGVCRES"
     gene            137377..138896
                     /gene="jgi.p|Lepmu1|2"
                     /locus_tag="gene_2"
     mRNA            join(137377..137570,137683..137882,138004..138896)
                     /gene="jgi.p|Lepmu1|2"
                     /locus_tag="gene_2"
                     /product="hypothetical protein"
     CDS             join(137377..137570,137683..137882,138004..138896)
                     /gene="jgi.p|Lepmu1|2"
                     /locus_tag="gene_2"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:gene_2-T1"
                     /translation="MRDLRRQALESHKTVSRKARSRIVSTAASKSNSAAASPAQSRAA
                     SRTRPVSDDDEEYHSDGTAMSTNSIDDVINGEDVDIPEGAWKAELNTRIEQITNLKRS
                     STEGRAESLNAYTHILMARYAKDEIEVHITLGVTILTLDSADIYDDIADQLKRSIQSS
                     TSVEVKANAIYTLGLAASFAGAGDDEILDIMNFFLEIVESDGASVDAQDDSDVVIAAL
                     EQWGLLATQIEDLEDETEAAVEAFVEQLESADSGVQVAAGENIALLYEKSYTAVEADD
                     EEPSDADDSDDPEVVKDDIRMVKRYQVYRRQDQLLHTLDGLASVSTRRISKKDRKTLH
                     SSFVDVRNSVERPTRGPGYSTTLDKETGKAKGAGTIEVRINSGVVVRIDKWWKLLRMN
                     ALRRTLQGGFTYHYDQNETVSSVLPFTMSRRVKTTK"
`
Thanks,
Fuyou

**Comment by axbazin** [comment]
Hello,

This looks like an annotation tool for Eucaryotes, and so does the file. PPanGGOLiN is originally made for procaryotes, so our parser is not made for parsing stuff like spliced genes and so on, like you have on "gene_2" in your example I believe.
It is likely that the gff parser passed without error but has done some erroneous things in the process, like translating introns or things like that.

Sorry, I cannot be of much help here. The only way for you to use PPanGGOLiN if you are indeed working on an Eucaryote genome is to provide the gff files (like you have tested) AND provide the clustering file for the cluster step. That way, the gene sequences won't be used and PPanGGOLiN should correctly partition your pangenome. It is however quite tedious to do.

Adelme
