### ISSUE TITLE
nucleotide or protein clustering?

### ISSUE THREAD

**Issue by zakisaati** [labgem/PPanGGOLiN#52]
Hi there,

Based on the article and the descriptions on github thought that ppanggolin made the clustering step based nucleotide gene sequences. However, I am confusing because of this sentence on this secction:

PanGGOLiN will call MMseqs2 to run the clustering on all the gene sequences using their greedy set cover algorithm for the clustering step. You can tune its parameters using --identity(default 0.8) and --coverage(default 0.8). **Both proteins** have to be covered by at least the proportion indicated by --coverage

Here it is said "Both proteins", which may be counfusing...
Could you please confirm me what kind of clustering does ppanggolin perform, please?

Thank you in advance

**Comment by axbazin** [comment]
Hi,

PPanGGOLiN clusters amino acid sequences. I'll go through the github descriptions to see if I can make this clearer later.

Adelme

**Comment by axbazin** [comment]
I'm noticing now that the 'cluster' part of the wiki is not up to date at all, I'll update it today.
