### ISSUE TITLE
Locus Tags vs Gene_ids

### ISSUE THREAD

**Issue by harish0201** [labgem/PPanGGOLiN#53]
Hi!

I'm using PPanGGoLin for some time and I'm really loving the tool and the ease of use.

I searched for this issue but I wasn't able to find, so here it goes.

We get the locus tags when using GenBank, however, is there a way to obtain the gene identifiers directly?

Locus tags are identified with /locus and genes with /gene in genbank.

**Comment by axbazin** [comment]
Hi !

If i'm not mistaken, the /gene from genbank files often corresponds to gene names, and it is often not unique within genbank (genes in different genomes can have the same gene name). it is parsed and saved in the .h5 file though, but not reported in many of the files.

In which files or figures are you looking for those gene identifiers ? 

Adelme

**Comment by harish0201** [comment]
I was looking at the families and the presence absence matrix. It would be much better if the gene names is placed rather than the locus tags.

**Comment by axbazin** [comment]
I understand. Indeed it would be much more practical to know what we are manipulating directly, as gene names are more explicit than locus tags.
It is not currently doable with the current version of ppanggolin, but it is definitely possible to code it. I will ask the other members of the project what they think about it and see if I can code that at some point in the near futur.

In the mean time I'm afraid there are no easy way to do it with ppanggolin currently, sorry.

**Comment by axbazin** [comment]
After discussing with other members of the project, there's actually a file that can help you, the 'matrix.csv' file which indicates, among many other information, the gene family id and the most common gene name in the cluster.

I do agree that have gene names directly would make it much more practical to know what you are looking at.

Using the 'matrix.csv' is not the same as naming clusters with the gene names, but for many reasons we will not do it, the first one being that gene names are sadly not unique.

While it will not be a ppanggolin default behavior, I guess that a script that generates the presence_absence matrix with informations from the matrix.csv file could be a nice add-on at some point in the futur, but for now this won't be done.

**Comment by fwhelan** [comment]
Hello. I just wanted to second this. I completely understand that gene names aren't unique, but I wonder if the most common gene name in the cluster could perhaps be appended in displays such as the tile plot (in a similar way to how they are present as extra info in the graph)? For example, I'm currently looking at a really well conserved/closed pangenome where a few strains are missing a small chunk of gene families; its harder to immediately link the result to the potential biological implications without some idea of which gene families are missing.
Thanks for considering!

**Comment by JeanMainguy** [comment]
Hi Fiona ! 
Thank you for suggesting this improvement. It would be indeed helpful.
I created a new issue #251 with your suggestion
