### ISSUE TITLE
Enhance drawing spot in plot

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#57]
# Function

`ppanggolin spot -p pangenome.h5 --draw_hotspots`

# Proposition 1

The plot contains in the label columns, the information of the genome(s) that contains the gene structure present in the line.

I propose to remove the number (1X, 2X, 3X,...) of genome that contains the gene structure in the label by the complete list of genomes or change it by a new label (like 'Structure_1', 'Structure_2') for each line and write the corresponding genomes association in a `.tsv` file for each spot.

# Proposition 2

With the annotation done by Prokka, the gene annotation is `MYSTRAIN_CDS_151354` in PPanGGOLiN. This tag is a bit longer
than the image can draw and result a troncate of gene annotation in the plot.

![image](https://user-images.githubusercontent.com/12897327/109291089-d0adad00-7828-11eb-91dd-262045cbdb76.png)

Maybe is it possible to have the upper marge more important.

Have a good day.

**Comment by axbazin** [comment]
Thanks a lot for the ideas.

Detecting the necessary margin could be something doable, and for the 2X, 3X... things in the plot I agree that not knowing which RGPs or genomes are behind can be quite unpractical.

**Comment by axbazin** [comment]
Hi,
The latest commit adresses the first point. for each drawn spot there will an additional file  'spot_y_identical_rgps.tsv' (y being the spot id) written indicating RGP ids, and genomes those RGP are found in, that are identical to one of the drawn RGP.

The format is as follow:
- representative RGP id
- representative genome name in which the RGP is
- identical RGP
- genome name in which the identical RGP is

I'll address the second problem soonish hopefully

Adelme

**Comment by axbazin** [comment]
Hi,
The old 'spot drawing' using R was removed and replaced by an option in 'ppanggolin draw' which draws interactive plots of spots. Those spots can be modified by users relatively easily, so the problems with margins or labels should not exist (and if they do, it should be possible to address it by changing some parameters directly in the interactive plots).
Adelme
