### ISSUE TITLE
add the possibility to use 'align' even when the clustering is not performed through PPanGGOLiN

### ISSUE THREAD

**Issue by axbazin** [labgem/PPanGGOLiN#58]
Mentionned in #56 (34th comment)

Being able to use 'align' when using an external clustering would be quite useful. 

Possibilities of realizing that are either by choosing a representative sequence for each cluster somehow, or use all genes instead of a representative for the aligning part. Doing the latter should not take too long as this is not traditionally used with a lot of protein sequences as input.

**Comment by IsabelFE** [comment]
Yeah, I can see how that might take more work. Thanks for considering this for future updates.

Regards.

**Comment by axbazin** [comment]
I know it's been a while, but this actually became possible a few releases ago (I think https://github.com/labgem/PPanGGOLiN/releases/tag/2.1.0 ?) when we changed the methods for "align", and more recently where we added the possibility for the user to provide their representative sequence.

So closing this now !
