### ISSUE TITLE
conda/mamba pyhton_abi problems 

### ISSUE THREAD

**Issue by shn89** [labgem/PPanGGOLiN#59]
Hi, 
I'm not able to get a newer than ppanggolin 1.0.13 installed with either conda or mamba in a completely new conda env. 
With mamba python-3.9.2 is installed and python_abi 3.9-1. But then mamba complains about the pyhton_abi (Problem: nothing provides python_abi 3.6.* *_cp36m needed by ppanggolin-1.1.136-py36h4c5857e_0), however when downgrading to pyhton 3.6 and python_abi 3.6, it complains again and requires python_abi 3.7 (Problem: nothing provides python_abi 3.7.* *_cp37m needed by ppanggolin-1.1.136-py37hf01694f_0) and this circles back to pyhton_abi 3.6 when upgrading to python 3.7. I've tried several times and different versions of both pyhton and ppanggolin witout any luck. 
Anything to do or should I try it from source?
Sofie

**Comment by axbazin** [comment]
Hi,

This seems rather strange, the recipe in conda allows only for python 3.6 and python 3.7 (since they are the only two python versions supported in bioconda, where the ppanggolin recipe is hosted), it should not try to install python 3.9.

The 'nothing provides xxx' message usually comes from missing channels.

If you have tried:

```
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels r

conda create -n pang-env --show-channel-urls --strict-channel-priority ppanggolin
```
and it does not work, could you write the conda log here ? I doubt that I will have any good advice though
Be wary that the 'conda config' commands listed here will change your channel priority.

Adelme

**Comment by shn89** [comment]
Hi,
yes I have all the channels open and just tried again with the channel
options, but unfortunately the same result. I don't have permission to the
anaconda.log on this server, unless there's some other way than looking in
the one in /var/log/anaconda.log, which would also be for many shared env
on the server.
Sofie


Den tor. 18. mar. 2021 kl. 11.34 skrev Adelme Bazin <
***@***.***>:

**Comment by axbazin** [comment]
If it's a linux server, if the GNU coreutils tools are installed (they usually are by default) and assuming you see the log when you launch the conda commands, you can run

`
conda create -n pang-env --show-channel-urls --strict-channel-priority ppanggolin | tee pango_install_conda.log
`

which will create a file called 'pango_install_conda.log' where the log of the executed command will be written.

**Comment by shn89** [comment]
Yes it is a  Linux server, should have GNU. I’ll try later and let you
know, thanks

tor. 18. mar. 2021 kl. 12.18 skrev Adelme Bazin ***@***.***>:

**Comment by shn89** [comment]
Hi,
I tried with yet another new env, but the config saved with tee is only of
the creation of the env and not following installations, therefore I have
copied the output into a self made log file for you, this I think is the
best I can do.
Best, Sofie

Den tor. 18. mar. 2021 kl. 12.30 skrev Sofie Holtsmark Nielsen <
***@***.***>:

**Comment by axbazin** [comment]
Hi,

I'm sorry I can't find any file associated to the issue. If you've shared it by email-answering to the issue I'm not sure it is supported by github.

Best,
Adelme

**Comment by shn89** [comment]
(FBI) shon@s-calc-fat01-p:/srv/data/tools/anaconda3/envs $ conda create -n env_ppanggolin --show-channel-urls --strict-channel-priority ppanggolin | tee pango_install_conda.log
Collecting package metadata: ...working... done
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - ppanggolin
Use "conda search <package> --info" to see the dependencies for each package.

(FBI) shon@s-calc-fat01-p:/srv/data/tools/anaconda3/envs $ conda create -n env_ppanggolin --show-channel-urls --strict-channel-priority | tee pango_install_conda.log
Collecting package metadata: ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/data/tools/anaconda3/envs/env_ppanggolin



Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate env_ppanggolin
#
# To deactivate an active environment, use
#
#     $ conda deactivate



##################just as an example I tried what happend if I tried to get python first from bioconda, but the version proposed is still 3.9.2
(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ conda install -c bioconda python
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/data/tools/anaconda3/envs/env_ppanggolin

  added / updated specs:
    - python


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    libstdcxx-ng-9.1.0         |       hdf63c60_0         4.0 MB
    ------------------------------------------------------------
                                           Total:        12.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.1.19-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py39h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1j-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.0.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.2-hdb3f193_0
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py39h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.35.1-hdfb4753_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  tzdata             pkgs/main/noarch::tzdata-2020f-h52ac0ba_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ conda install mamba
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/data/tools/anaconda3/envs/env_ppanggolin

  added / updated specs:
    - mamba


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  brotlipy           pkgs/main/linux-64::brotlipy-0.7.0-py39h27cfd23_1003
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  c-ares             pkgs/main/linux-64::c-ares-1.17.1-h27cfd23_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.1.19-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py39h06a4308_0
  cffi               pkgs/main/linux-64::cffi-1.14.5-py39h261ae71_0
  chardet            pkgs/main/linux-64::chardet-4.0.0-py39h06a4308_1003
  conda              pkgs/main/linux-64::conda-4.9.2-py39h06a4308_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.7.2-py39h27cfd23_1
  cryptography       pkgs/main/linux-64::cryptography-3.4.6-py39hd23ed53_0
  icu                pkgs/main/linux-64::icu-58.2-he6710b0_3
  idna               pkgs/main/noarch::idna-2.10-pyhd3eb1b0_0
  krb5               pkgs/main/linux-64::krb5-1.17.1-h173b8e3_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libarchive         conda-forge/linux-64::libarchive-3.5.1-h899b81a_0
  libcurl            conda-forge/linux-64::libcurl-7.75.0-hc4aaa36_0
  libedit            pkgs/main/linux-64::libedit-3.1.20210216-h27cfd23_1
  libev              pkgs/main/linux-64::libev-4.33-h7b6447c_0
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_18
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_18
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  libnghttp2         conda-forge/linux-64::libnghttp2-1.43.0-h812cca2_0
  libsolv            conda-forge/linux-64::libsolv-0.7.17-h780b84a_1
  libssh2            pkgs/main/linux-64::libssh2-1.9.0-h1ba5d50_1
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_18
  libxml2            pkgs/main/linux-64::libxml2-2.9.10-hb55368b_3
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.2-heb0550a_3
  lzo                pkgs/main/linux-64::lzo-2.10-h7b6447c_2
  mamba              conda-forge/linux-64::mamba-0.8.2-py39h951de11_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1j-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.0.1-py39h06a4308_0
  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py39h27cfd23_0
  pycparser          pkgs/main/noarch::pycparser-2.20-py_2
  pyopenssl          pkgs/main/noarch::pyopenssl-20.0.1-pyhd3eb1b0_1
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.2-hdb3f193_0
  python_abi         conda-forge/linux-64::python_abi-3.9-1_cp39
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  reproc             conda-forge/linux-64::reproc-14.2.1-h36c2ea0_0
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.1-h58526e2_0
  requests           pkgs/main/noarch::requests-2.25.1-pyhd3eb1b0_0
  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.80-py39h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py39h06a4308_0
  six                pkgs/main/noarch::six-1.15.0-pyhd3eb1b0_0
  sqlite             pkgs/main/linux-64::sqlite-3.35.1-hdfb4753_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  tqdm               pkgs/main/noarch::tqdm-4.59.0-pyhd3eb1b0_1
  tzdata             pkgs/main/noarch::tzdata-2020f-h52ac0ba_0
  urllib3            pkgs/main/noarch::urllib3-1.26.4-pyhd3eb1b0_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
  zstd               pkgs/main/linux-64::zstd-1.4.5-h9ceee32_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ mamba install -c bioconda ppanggolin=1.1.136

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ppanggolin=1.1.136']

r/noarch                 [====================] (00m:00s) Done
r/linux-64               [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
bioconda/noarch          [====================] (00m:00s) Done
bioconda/linux-64        [====================] (00m:00s) Done
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done
Encountered problems while solving.
Problem: nothing provides colorlover 0.3.* needed by ppanggolin-1.1.136-py36h4c5857e_0

(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ mamba install -c conda-forge colorlover

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['colorlover']

r/linux-64               Using cache
r/noarch                 Using cache
pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/linux-64     [====================] (00m:03s) Done
Transaction

  Prefix: /srv/data/tools/anaconda3/envs/env_ppanggolin

  Updating specs:

   - colorlover


  Package       Version  Build           Channel                    Size
──────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────

  colorlover      0.3.0  py_0            conda-forge/noarch        12 KB

  Change:
──────────────────────────────────────────────────────────────────────────

  certifi     2020.12.5  py39h06a4308_0  installed
  certifi     2020.12.5  py39hf3d152e_1  conda-forge/linux-64     143 KB
  openssl        1.1.1j  h27cfd23_0      installed
  openssl        1.1.1j  h7f98852_0      conda-forge/linux-64       2 MB

  Summary:

  Install: 1 packages
  Change: 2 packages

  Total download: 2 MB

──────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Finished colorlover                           (00m:00s)              12 KB     57 KB/s
Finished certifi                              (00m:00s)             143 KB    680 KB/s
Finished openssl                              (00m:01s)               2 MB      7 MB/s
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ mamba install -c bioconda ppanggolin=1.1.136

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ppanggolin=1.1.136']

bioconda/linux-64        Using cache
bioconda/noarch          Using cache
r/linux-64               Using cache
r/noarch                 Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
Encountered problems while solving.
Problem: nothing provides python_abi 3.6.* *_cp36m needed by ppanggolin-1.1.136-py36h4c5857e_0

(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ conda install -c bioconda python=3.6
Collecting package metadata: \ failed

CondaError: KeyboardInterrupt

(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ mamba install -c bioconda python=3.6

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.6']

bioconda/linux-64        Using cache
bioconda/noarch          Using cache
r/linux-64               Using cache
r/noarch                 Using cache
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
Encountered problems while solving.
Problem: package python_abi-3.9-1_cp39 requires python 3.9.*, but none of the providers can be installed

(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ mamba install -c conda-forge python=3.6

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.6']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
r/linux-64               Using cache
r/noarch                 Using cache
pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache
Transaction

  Prefix: /srv/data/tools/anaconda3/envs/env_ppanggolin

  Updating specs:

   - python==3.6


  Package                   Version  Build               Channel                    Size
──────────────────────────────────────────────────────────────────────────────────────────
  Change:
──────────────────────────────────────────────────────────────────────────────────────────

  brotlipy                    0.7.0  py39h27cfd23_1003   installed
  brotlipy                    0.7.0  py36he6145b8_1001   conda-forge/linux-64     347 KB
  certifi                 2020.12.5  py39hf3d152e_1      installed
  certifi                 2020.12.5  py36h5fab9bb_1      conda-forge/linux-64     143 KB
  cffi                       1.14.5  py39h261ae71_0      installed
  cffi                       1.14.5  py36hc120d54_0      conda-forge/linux-64     225 KB
  chardet                     4.0.0  py39h06a4308_1003   installed
  chardet                     4.0.0  py36h5fab9bb_1      conda-forge/linux-64     219 KB
  conda                       4.9.2  py39h06a4308_0      installed
  conda                       4.9.2  py36h5fab9bb_0      conda-forge/linux-64       3 MB
  conda-package-handling      1.7.2  py39h27cfd23_1      installed
  conda-package-handling      1.7.2  py36he6145b8_0      conda-forge/linux-64     925 KB
  cryptography                3.4.6  py39hd23ed53_0      installed
  cryptography                3.4.6  py36hb60f036_0      conda-forge/linux-64       1 MB
  mamba                       0.8.2  py39h951de11_0      installed
  mamba                       0.8.2  py36h05d92e0_0      conda-forge/linux-64     642 KB
  pip                        21.0.1  py39h06a4308_0      installed
  pip                        21.0.1  pyhd8ed1ab_0        conda-forge/noarch         1 MB
  pycosat                     0.6.3  py39h27cfd23_0      installed
  pycosat                     0.6.3  py36h8f6f2f9_1006   conda-forge/linux-64     107 KB
  pysocks                     1.7.1  py39h06a4308_0      installed
  pysocks                     1.7.1  py36h5fab9bb_3      conda-forge/linux-64      27 KB
  setuptools                 52.0.0  py39h06a4308_0      installed
  setuptools                 52.0.0  py36h06a4308_0      pkgs/main/linux-64       724 KB

  Upgrade:
──────────────────────────────────────────────────────────────────────────────────────────

  ld_impl_linux-64           2.33.1  h53a641e_7          installed
  ld_impl_linux-64           2.35.1  hea4e1c9_2          conda-forge/linux-64     618 KB
  ruamel_yaml               0.15.80  py39h27cfd23_0      installed
  ruamel_yaml               0.15.87  py36h7b6447c_1      pkgs/main/linux-64       244 KB

  Downgrade:
──────────────────────────────────────────────────────────────────────────────────────────

  python                      3.9.2  hdb3f193_0          installed
  python                     3.6.13  hffdb5ce_0_cpython  conda-forge/linux-64      38 MB
  python_abi                    3.9  1_cp39              installed
  python_abi                    3.6  1_cp36m             conda-forge/linux-64       4 KB

  Summary:

  Change: 12 packages
  Upgrade: 2 packages
  Downgrade: 2 packages

  Total download: 48 MB

──────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Finished setuptools                           (00m:01s)             724 KB      8 MB/s
Finished python_abi                           (00m:01s)               4 KB     34 KB/s
Finished certifi                              (00m:02s)             143 KB      1 MB/s
Finished ld_impl_linux-64                     (00m:02s)             618 KB      4 MB/s
Finished brotlipy                             (00m:02s)             347 KB      2 MB/s
Finished pycosat                              (00m:02s)             107 KB    455 KB/s
Finished pip                                  (00m:05s)               1 MB      4 MB/s
Finished chardet                              (00m:06s)             219 KB    750 KB/s
Finished cffi                                 (00m:06s)             225 KB    759 KB/s
Finished mamba                                (00m:06s)             642 KB      2 MB/s
Finished pysocks                              (00m:06s)              27 KB     77 KB/s
Finished cryptography                         (00m:10s)               1 MB      3 MB/s
Finished conda                                (00m:15s)               3 MB      7 MB/s
Finished conda-package-handling               (00m:15s)             925 KB      2 MB/s
Finished ruamel_yaml                          (00m:16s)             244 KB    527 KB/s
Finished python                               (00m:33s)              38 MB     18 MB/s

Downloading and Extracting Packages
idna-2.10            | 52 KB     | ################################################################################################ | 100%
requests-2.25.1      | 51 KB     | ################################################################################################ | 100%
pycparser-2.20       | 94 KB     | ################################################################################################ | 100%
six-1.15.0           | 13 KB     | ################################################################################################ | 100%
wheel-0.36.2         | 31 KB     | ################################################################################################ | 100%
tqdm-4.59.0          | 90 KB     | ################################################################################################ | 100%
pyopenssl-20.0.1     | 48 KB     | ################################################################################################ | 100%
urllib3-1.26.4       | 99 KB     | ################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $ mamba install -c bioconda ppanggolin=1.1.136

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████
bioconda/linux-64        Using cache
bioconda/noarch          Using cache
r/linux-64               Using cache
r/noarch                 Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change


Looking for: ['ppanggolin=1.1.136']

Encountered problems while solving.
Problem: nothing provides python_abi 3.7.* *_cp37m needed by ppanggolin-1.1.136-py37hf01694f_0

(env_ppanggolin) shon@s-calc-fat01-p:/srv/data/FBI $

**Comment by axbazin** [comment]
Thanks a lot !

I tried the same command as you did and encountered an issue, using the '--no-channel-priority' solved it for me, though I'm not sure I understand where the issue lies.

For some reason your first two mamba command did not search the 'conda-forge' channel, while it did in the command just before, so this is probably why colorlover was not found (as it is hosted in conda-forge)

My guess is maybe this might work, it did for me with a 'cleaned' conda and no channels set up:
``` mamba create -n ppanggolin_env -c bioconda -c conda-forge -c r --no-channel-priority ppanggolin=1.1.136 ```

Adelme

**Comment by shn89** [comment]
That did the trick! Thanks!
Because of the setup of our server I ended up doing this.

conda create -y -n env_ppanggolin
conda activate env_ppanggolin
conda install -c conda-forge mamba
mamba install -c conda-forge python=3.7
mamba install -c bioconda -c conda-forge -c r --no-channel-priority
ppanggolin=1.1.136



Den tor. 18. mar. 2021 kl. 17.17 skrev Adelme Bazin <
***@***.***>:
