### ISSUE TITLE
Ppackage ppanggolin-v0.3.88-py37h01d97ff_0 requires pytables 3.5.*, but none of the providers can be installed

### ISSUE THREAD

**Issue by suryatri1** [labgem/PPanGGOLiN#60]
<img width="845" alt="Screen Shot 2021-03-25 at 1 38 24 PM" src="https://user-images.githubusercontent.com/47872415/112540912-f9fe2200-8d6f-11eb-97e5-5cff9507ec58.png">
I am trying to install Ppanggolin on my MacOS Catalina (OSx64) through mamba but I keep getting this error. Please let me know how I could address this issue. Thank you so much for your time.

**Comment by axbazin** [comment]
Hello,

I do not see what command you used but I'm going to guess it is the one in the readme. 

Here it seems that it did not find the latest version for some reason.

I'm guessing maybe this might help:
```
mamba install -c bioconda -c conda-forge -c r ppanggolin=1.1.136
```

If it tells you again about requiring some packages it cannot install, the last time someone had troubles with install using the option `--no-channel-priority` made it work, so you can try that as well.

Good luck,
Adelme

**Comment by geronimp** [comment]
Hi there, I'm also encountering this issue while installing. I attempted the commands suggested above, but still no luck unfortunately.

**Comment by axbazin** [comment]
Hi,

I'll try to get access a macOS catalina somehow to test things out.
In the meantime I can't do much more since I can't replicate this behavior on linux, sorry.

Adelme

**Comment by axbazin** [comment]
Hi,

Finding a macOS Catalina machine was surprisingly easier than I expected. It did replicate the error.

The problem comes from having a python version that is not supported by bioconda (where ppanggolin conda recipe is hosted)
installing a new env with a fixed python version solved the problem:

```
mamba create -n ppanggolin_env python=3.7
mamba install -n ppanggolin_env -c bioconda -c conda-forge -c r ppanggolin=1.1.136
```

Adelme

**Comment by suryatri1** [comment]
Aweseome, that worked. Thanks a lot!
