### ISSUE TITLE
Data of gexf/light_gexf I can get

### ISSUE THREAD

**Issue by mhjonathan** [labgem/PPanGGOLiN#76]
Hi,

I'm using the PPanGGOLiN for visualizing physical location of gene families. I tried to make light_gexf networks using Gephi with 3 different datasets, and I find out that one of light_gexf file contains node information of Number of triangle, Degree, Weighted degree.. which are not included in other light_gexf files even though all they got through same commands and parameters (I confirmed that they have same parameters with command: ppanggolin info -p pangenome.h5 --parameters.

The information (Number of triangle, Degree..) are exactly what I'm looking for, so how can I get all these data from other datasets too? 

Below is the commands for 2 datasets without containing the information:

ppanggolin annotate --anno MAGs_gff_Input.txt --output MAGs_all --cpu 30
ppanggolin cluster -p MAGs_all/pangenome.h5 --clusters MAG_GeneFamily_all.txt --infer_singletons --cpu 30
ppanggolin graph -p MAGs_all/pangenome.h5 --cpu 30
ppanggolin partition -p MAGs_all/pangenome.h5 --cpu 30
ppanggolin rgp -p MAGs_all/pangenome.h5
ppanggolin write -p MAGs_all/pangenome.h5 --regions --output -f MAGs_all
ppanggolin spot -p MAGs_all/pangenome.h5
ppanggolin draw -p MAGs_all/pangenome.h5 --cpu 30 --output MAGs_all --tile_plot --ucurve --spots all -f
ppanggolin write -p MAGs_all/pangenome.h5 --cpu 30 --light_gexf --output MAGs_all -f
ppanggolin write -p MAGs_all/pangenome.h5 --cpu 30 --gexf --output MAGs_all -f
ppanggolin module -p MAGs_all/pangenome.h5
ppanggolin write -p MAGs_all/pangenome.h5 --modules --output MAGs_all -f
ppanggolin write -p MAGs_all/pangenome.h5 --spot_modules --output MAGs_all -f
ppanggolin write -p MAGs_all/pangenome.h5 --csv --output MAGs_all -f
ppanggolin write -p MAGs_all/pangenome.h5 --partitions --output MAGs_all -f

And this is the commands for the dataset containing the information:

ppanggolin annotate --anno MAGs_gff_Input_Case.txt --output MAGs_Case --cpu 30
ppanggolin cluster -p MAGs_Case/pangenome.h5 --clusters MAG_GeneFamily_Ac.txt --infer_singletons --cpu 30
ppanggolin graph -p MAGs_Case/pangenome.h5 --cpu 30
ppanggolin partition -p MAGs_Case/pangenome.h5 --cpu 30
ppanggolin rgp -p MAGs_Case/pangenome.h5
ppanggolin write -p MAGs_Case/pangenome.h5 --regions --output -f MAGs_Case
ppanggolin spot -p MAGs_Case/pangenome.h5
ppanggolin draw -p MAGs_Case/pangenome.h5 --cpu 30 --output MAGs_Case --tile_plot --ucurve --spots all -f
ppanggolin write -p MAGs_Case/pangenome.h5 --cpu 30 --light_gexf --output MAGs_Case -f
ppanggolin write -p MAGs_Case/pangenome.h5 --cpu 30 --gexf --output MAGs_Case -f
ppanggolin module -p MAGs_Case/pangenome.h5 --cpu 30
ppanggolin write -p MAGs_Case/pangenome.h5 --modules --output MAGs_Case -f
mkdir MAGs_Case/spot_plots
ppanggolin write -p MAGs_Case/pangenome.h5 --spot_modules --output MAGs_Case/spot_plots -f --cpu 30
ppanggolin write -p MAGs_Case/pangenome.h5 --csv --output MAGs_Case -f --cpu 30
ppanggolin write -p MAGs_Case/pangenome.h5 --partitions --output MAGs_Case -f --cpu 30

**Comment by jpjarnoux** [comment]
Hi, 
I don't see any reason why there is different information. I will look for the reason. 
It's possible to share your both pangenome.h5 file ?
Thanks

**Comment by axbazin** [comment]
Hi,

Can it be additional info added by Gephi then saved into the gexf file by Gephi? It sounds like metrics computed after the original gexf file writing, I don't think that there is any code dedicated to finding triangles or weighted degree in ppanggolin.

Adelme

**Comment by ggautreau** [comment]
Hi,

Sorry for the delayed answer, did not see the issue before.

As said by @axbazin, `Number of triangle`, `Degree` and `Weighted degree` are metrics only added by Gephi. Maybe in some case you computed these statistics using Gephi and not in the others cases.

However, I think it would be easy to add them to PPanGGOLiN in a next version if there is a need for that.

Best regards.
