### ISSUE TITLE
Suggestion : Add length gene on Bokeh Spot frame

### ISSUE THREAD

**Issue by Nilad** [labgem/PPanGGOLiN#77]
Hello =)

It is possible to add just bellow the start and stop information field (and above to the gene name) on the Bokeh dynamic "gene" frame the length of the "gene" ? 

This information can be very useful in case of truncate gene or to compare gene variant with alternative start/stop codon.

Thanks in advance.

Have a good day.

**Comment by jpjarnoux** [comment]
Hi, I made a quick change in a new branch GeneLength. Could you test if the result is what you're expected ? 
You can make this to install a local version of ppanggolin with the new information :
```
#if you already clone ppanggolin git
cd path/to/ppanggolin/directory
#if you don't 
git clone https://github.com/labgem/PPanGGOLiN.git
cd PPanGGOLiN
#After
git fetch origin
git checkout GeneLength
pip install .
# Now you can test the command, it should be the 1.2.78 version of PPanGGOLiN
```
If you have any trouble or more suggestion, don't hesitate to post here.

**Comment by axbazin** [comment]
Closing at it's now in master, and soon in the next release
