### ISSUE TITLE
coverage badge and no test ?

### ISSUE THREAD

**Issue by sletort** [labgem/PPanGGOLiN#8]
hi, I like this soft.  
What the coverage badge for ? i didn't see any test.  

I'd like to make my #Hacktoberfest2019 on your project, will you accept unit tests ?  Any other simple ideas/needs ?

**Comment by axbazin** [comment]
Hi, thank you for this nice comment.

The coverage badge comes from codacy, which I use for code review. Tests are ran locally using coverage.py. I've not pushed any of the tests to this repo however as you noticed.

Including tests in the repo sounds nice (and should probably have been done from the start), if you do want to include unit tests using another library you are more than welcome to add them. If you're interested I'll update the testing dataset on this repo and/or can send you what I'm running for tests at the moment.

I have no ideas for 'simple' additions other than that.

**Comment by sletort** [comment]
Ok, i didn't know coverage.py could be run without test. I always used it through pytest-cov.  
So I'll propose unit test.
