### ISSUE TITLE
Partitioning

### ISSUE THREAD

**Issue by seajane** [labgem/PPanGGOLiN#80]
I have run into the situation several times during the partitioning of the pangenome where I allow it to choose the optimal number of partitions and it chooses 5, but will only partition into 3 parts (persistent, shell and cloud).  If I try to set the partitioning to any number over 2 it will partition into 3 parts.  Is there a setting that I am missing or need to optimize?  Thanks in advance!

**Comment by seajane** [comment]
In a related question, a folder is created but no image when using the `ppanggolin partition -p pangenome.h5 -- draw_ICL` option

**Comment by seajane** [comment]
Here's some info to provide context: 
`Genes : 161288
Organisms : 74
Families : 7367
Edges : 12617
Persistent ( min:0.77, max:1.0, sd:0.03, mean:0.99 ): 1398
Shell ( min:0.18, max:0.85, sd:0.16, mean:0.49 ): 788
Cloud ( min:0.01, max:0.35, sd:0.06, mean:0.06 ): 5181
<img width="1612" alt="Screen Shot 2022-04-05 at 8 42 42 PM" src="https://user-images.githubusercontent.com/8787869/161891736-acbca633-2afa-4d79-b092-9a44c9a079b2.png">

Number of partitions : 3`

**Comment by seajane** [comment]
Unfortunately even in the `ppanggolin write -p pangenome.h5 --partitions` there is only one "shell.txt" and one "S.txt". I am hoping to separate out the different parts of the shell into two or three parts, but cannot seem to access that functionality.

**Comment by axbazin** [comment]
Alright, I think I found the issue, the reason behind this is the modification of the -ck parameter. This should be useful only when doing large (i.e. more than 500 genomes) pangenomes. In your case, you should stick with the default behavior.

The reason behind this is that when there are very large pangenomes the statistical model starts to struggle, so we do sampling among the genomes multiple time and gather the results. When doing so, we do not have access to the subpartitions anymore.
 This -ck option controls only the size of the sampling.

In your case, with 74 genomes the statistical model should work fine, and you should not do sampling. You're probably better off not changing that option.

When leaving it at 500, you should get subpartitions for your pangenome as it will not sample among the genomes during the partition step.

Hopefully that solves this problem and you get S1, S2... partitions and so on.

Adelme

**Comment by seajane** [comment]
Adelme,
Thank you for your reply. I began using the -ck parameter subsequent to finding myself unable to produce S1, S2 shells in ppanggolin. It has the effect of shrinking the size of the shell,  when I use it in sizes closer to the number of strains in my smallest expected partition, the -ck parameter has the (unintended) effect of reducing the shell to those genes that are present/absent in almost all of one group.  That said, whether I use it or not, I am still unable to create S1, S2 shells even if the default partition finds 5.

**Comment by jpjarnoux** [comment]
Hello, 
As Adelme said, there were some problems saving the partition information. That's why (in addition to the reason given by Adelme with the `--ck` option), when you did `ppanggolin write -p pangenome.h5 --partitions` there was only one "S.txt" file and no others. I fixed this in the related `80-partitioning` branch. You can test the correction by running in your PPanGGOLiN directory: 
```
git fetch
git checkout 80-partitioning
pip install .
ppanggolin partition -p path/to/your/pangenome.h5 -K 5 --force
ppanggolin write -p pangenome.h5 --partitions
```
Please let us know if you encounter any difficulties. 

To draw the ICL, I could not reproduce the bug. Note that if you give the `-K` option, it is normal that you don't have an ICL because it doesn't draw. We should add an information message for the incompatibility of the options.

**Comment by seajane** [comment]
Thank you!! I let the default choose the number of partitions - this is perfect!!

Genes: 161288
Organisms: 74
Families: 7367
Edges: 12610
Persistent ( min:0.77, max:1.0, sd:0.03, mean:0.99 ): 1397
Shell ( min:0.11, max:0.88, sd:0.2, mean:0.31 ): 1819
Cloud ( min:0.01, max:0.12, sd:0.03, mean:0.04 ): 4151
Number of partitions: 5
Shell S3 : 1183
Shell S1 : 389
Shell S2 : 247

The ICL curve was drawn as well. Great work! Thanks!

**Comment by axbazin** [comment]
Awesome !

Don't hesitate to reopen the issue (or open a new one) if you still have troubles with this.
