### ISSUE TITLE
Only extract unique RGPs

### ISSUE THREAD

**Issue by genomesandMGEs** [labgem/PPanGGOLiN#84]
Hi there,

Many thanks for such a great tool!
Is it possible to extract RGPs that are uniquely found in single genomes from the pangenome? For example, if I build a pangenome starting from 20 genomes named _1 to _20, will it be possible to extract RGPs that are solely found in genome_1, but absent from the remaining 19 genomes? And do this recursively for all the genomes of the collection?

Thank you

**Comment by axbazin** [comment]
Hi,

Thank you !

It is possible to get that information, though only indirectly currently.
If you run the following command:

`ppanggolin draw --spots all`

It will draw all spots, and additionnaly write files "spot_X_identical_rgps.tsv", which lists all RGPs that are identical within each spot. You can look for RGPs that are uniquely present by checking those that appear uniquely in the first column.

However, if you follow this procedure and there are RGPs that are identical but present in different spots (so identical in gene composition, but their bordering genes are different), you will consider them as unique even if they are not. I'd expect that case to be relatively rare though, except for some MGEs maybe (though seeing your name on github that might be a problem).

Would that be a problem ? If it is, I don't know if there is a better alternative using ppanggolin's command line currently, but using PPanGGOLiN's python API it is likely possible to circumvent it.

Adelme

**Comment by genomesandMGEs** [comment]
Hi Adelme,

Many thanks for the quick reply. Next week I'll try your approach, and will let you know how it went.
Thanks again!

João Botelho, PharmD, PhD
Max Planck Institute for Evolutionary Biology,
24306 Ploen, Germany
Evolutionary Ecology and Genetics, CAU Kiel,
24118 Kiel, Germany
________________________________
