### ISSUE TITLE
huge difference in results with --fasta and --anno, question

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#87]
Hello,

I'm doing some tries with PPanGGOLiN and trying to understand how to optimize it for my dataset.
I made a try with exactly the same 50 genomes, first with the `ppanggolin all --fasta` option, and then a second try with `ppanggolin all --anno` option with gff files coming from prokka.
After I made a `ppanggolin metrics` for both cases and got huge differential results as you can see in the following table:

|                                |     --fasta    |       --anno     |
|--------------------------------|:--------------:|:----------------:|
|     #genes                     |     176,524    |     1,325,979    |
|     #families                  |      70,036    |      108,769     |
|     #persistent (most ind.)    |       564      |       4,167      |
|     #shell                     |       475      |       1,175      |
|     #cloud(few ind.)           |      68,997    |      103,427     |
|     #edges                     |      1,101     |      125,411     |
|     #RGP                       |        8       |       8,659      |
|     #Spots                     |        0       |        358       |
|     #Modules                   |        0       |       1,452      |
|     #Families in modules       |        0       |       13,441     |

I'm wondering why such a difference? Probably part of the answer is because the annotation is not made with the same software in both cases, but still, to me, it doesn't explain why we have such a difference. Do you have any idea?

**Comment by axbazin** [comment]
The difference does seem pretty massive, there is definitely a problem with what is given to --fasta.

Are the files given through --fasta the same files that were given to prokka ?
The gene caller in both cases is the same, prokka and ppanggolin both use Prodigal internally, so results should be very similar

**Comment by cmonat** [comment]
Thanks for your quick answer.
I'll investigate to be sure that the files are correct.

Anyway, if the results are very similar, the interest to choose such or such option is just related to the file format that we have? That is, if you have both types of files, no matter which option you use, the results will be essentially the same?

Have a great day
Regards
C.

**Comment by axbazin** [comment]
Yes absolutely, and also often there are additional analysis that you may want to conduct with other softwares depending on what you are working on. Providing the annotations through --anno is useful to keep the same identifiers, making subsequent analysis much easier when comparing what you get from PPanGGOLiN to your other results from other tools.

Furthermore, sometimes genomes are atypical (e.g. some people have worked with phage genomes using PPanGGOLiN in the past) so the ppanggolin annotation workflow will not work as well.

Overall, the --fasta option alone is there to run PPanGGOLiN "easily" on typical bacterial genomes, but the best approach is to use an annotation pipeline that fits your needs best, and provide the annotations files through --anno.

Have a good day too !
Adelme
