### ISSUE TITLE
What does this column mean?

### ISSUE THREAD

**Issue by TommyH-Tran** [labgem/PPanGGOLiN#91]
![gexf_table_SS](https://user-images.githubusercontent.com/60275107/180894354-cb0b73f0-4014-48e0-a225-df5210f67e95.png)

Hello, 

I am viewing a data table produced from PPanGGOLiN in Gephi.  What does column to the right of the "nb_organisms" mean? I see the genome of interest is the title , what do the contents within the cells below it mean? 

Also, for the "length" columns are those number of basepairs? Like average and median number of basepairs? 

Thanks!

**Comment by ggautreau** [comment]
Hi @TommyH-Tran,

The `nb_organisms` column means the number of genomes having at least one gene in a particular gene families

The genomes of interest are columns indeed and the content of the cells correspond to the ID of genes (concatenated by '|' if there are several genes) belonging to a particular gene families.

Yes, the length (mean ou median) corresponds to the number of basepairs.

Best.
